### ISSUE TITLE
Implement PSR-18 

### ISSUE THREAD

**Issue by damianopetrungaro** [pact-foundation/pact-php#100]
PSR 18 has been released, if you think it may be useful to include here I can open a PR to implement it.

https://www.php-fig.org/psr/psr-18/

**Comment by cfmack** [comment]
That's interesting.   It would be helpful if Guzzle or other implementations get updated and thus require pact-php to update too.   Thoughts?

**Comment by frastel** [comment]
Is there any real need for this implementation? If yes, pact-php would need a mechanism to configure the used client to profit from this change.

**Comment by YOU54F** [comment]
Hey all,

I'm doing a Pact-PHP issue clean, and as this request is a few years old and there hasn't been any traction on it one way or the other, I am going to close it down.

If any Pact-PHP users feel it would benefit to implement PSR-18, please fee free to comment, including your rationale and we can reopen if required
