### ISSUE TITLE
Pact files not written any more

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#107]
Hi there,

using any commits after https://github.com/pact-foundation/pact-php/commit/4004e443186737b9d6ae4cc61f42228c20f70331 break my test code in that pact files are no longer written to disk. Not sure how that would be affected but just switching back to the above commit makes things work again.
Any pointers as to how to debug this would be appreciated.

**Comment by cirnatdan** [comment]
Might be my PR that caused this (https://github.com/pact-foundation/pact-php/pull/98)
Will check this and let you know

**Comment by cfmack** [comment]
Wow, we have so many tests and missed this one :).   I am going to be traveling and won't be able to look into this for a few days.

**Comment by cfmack** [comment]
I think I can replicate this, @DerManoMann .  

1. The examples were written on Windows
1. The output pacts that the consumer tests generate were checked in
1. The phpunit.consumer.xml and phpunit.all.xml explicitly had Windows pathing: "PACT_OUTPUT_DIR" value=".\example\output\\"
1. The mock server is an instance of the Ruby server

Even when replacing the \ in the XML, .\example\output was called to the Ruby server.   When switching to Amp, somehow I assume, the directory pathing was not correct.   When running on Linux (which I assume you are doing), Ruby strips out the \ and the file output becomes .exampleoutput.   

I assume you have something similar as you noted the "defaults changed", which they seemed to by stripping out the extra \ .  

To be clear, this is *not* a bug of the Ruby server.

**Comment by cfmack** [comment]
@DerManoMann , I modified the pathing code and examples on 

explicitly changed pathing when calling ruby server #108

If this works for you, I'll make another tag.  Right now, it is hanging out on Master

**Comment by DerManoMann** [comment]
Hmm, tested this just now with
````
pact-foundation/pact-php           dev-master 3c234e7 Enables consumer driven contract testing, following the PACT foundation principles.
````
and still not seeing any files.
The CL looks like this and the path names are all correct. I also debugged and the change in `setPactDir()` doesn't seem to be making a difference anyway on linux.
````
server.DEBUG: Process command: /.../vendor/pact-foundation/pact-php/src/PhpPact/Standalone/Installer/../../../../pact/bin/pact-mock-service service --consumer=php-client --provider=api-service --pact-dir=/../pacts --pact-file-write-mode=merge --host=localhost --port=7200 --pact-specification-version=2 [] []
````

My understanding is that the mock server writes the files at the appropriate time. Since I have a somewhat custom phpunit integration and also a custom listener it might be that I am missing something there.

Where exactly is the code in the PHP library that will tell the mock server to write the files? Maybe that doesn't get triggered any more?

**Comment by bethesque** [comment]
At the end of the test, the test framework needs to send a POST to `/pact/write` if the tests have passed.

**Comment by bethesque** [comment]
There is also a shutdown hook that will execute if the mock service was started with the right info (consumer, provider, pact dir) and is shut down *gracefully*.

**Comment by DerManoMann** [comment]
I wonder if that gracefulness changed with the refactor - I cannot find any `/pact/write` references in the package and `MockServerHttpService`, which looks like the most obvious candidate for this, does not have a method for that

**Comment by cfmack** [comment]
@DerManoMann , can you post the code you are using? Are you calling the built in PactTestListener class or calling things directly (should be perfectly fine, btw)?

I updated the pact-php-example implementation in just the consumer version (part that writes the pact) in "example-one".  Here is the working https://github.com/cfmack/pact-php-example/tree/linux/example-one 

While I did not check on Windows, the tests on appveyor that run on Windows clearly create the file.

Can you clone the aforementioned git repo to replicate the issue?  All the tests and examples are working.  Perhaps we are now eating an error message or something similar.

**Comment by cfmack** [comment]
Also, according to your posted example, this is a really weird path:

--pact-dir=/../pacts

I am not sure what is before root

**Comment by cfmack** [comment]
> I wonder if that gracefulness changed with the refactor - I cannot find any `/pact/write` references in the package and `MockServerHttpService`, which looks like the most obvious candidate for this, does not have a method for that

Yes, I agree that is a natural candidate and is a good feature add.  I still cannot replicate the issue or get it to stop un-gracefully.   Files are being written accordingly locally and in the tests

**Comment by DerManoMann** [comment]
I am using merge as an alternative to re-using a mock server across multiple test cases. We ran into issues where the tests where reliably hanging after having more than 3/4 separate phpunit test classes in the suite.
With merge we can kick off a new mock server for each test and the results all get merged into a single file.

The path is stange looking as I had to remove some sensible bits and didn't manage to come up with some dummy value :/

If there is currently no code to actually force the server to write the results via `/pact/write` I'll hack something together. Right now that is the only things I can see left untried.

**Comment by DerManoMann** [comment]
Hmm, `/pact/write` does not work (neither get/post). Getting the JSON does and that looks legit.

Here is the code the custom listener uses to set up/start a mock server for each provider:
````
            $serverConfig = clone $this->defaultConfig;
            $serverConfig
                ->setProvider($provider)
                ->setPort($this->nextPort++);

            // start
            $server = new MockServer($serverConfig);
            if (!($pid = $server->start())) {
                throw new \RuntimeException('Could not start mock server');
            }

            // keep somewhere
            $this->serverDetails[$provider] = [
                'pid' => $pid,
                'server' => $server,
                'config' => $serverConfig,
            ];

````

And here the shutdown:
````
        foreach ($this->serverDetails as $provider => $serverDetails) {
            try {
                $httpService = new MockServerHttpService(new GuzzleClient(), $serverDetails['config']);
                $httpService->verifyInteractions();
            } finally {
                $serverDetails['server']->stop();
                unset($this->serverDetails[$provider]);
            }
        }
````

**Comment by bethesque** [comment]
Sorry, my bad. It's just a POST to `/pact`

https://github.com/pact-foundation/pact-ruby-standalone-e2e-example/blob/master/script/consumer-create-pact.sh#L19

**Comment by cfmack** [comment]
That the framework does call:  https://github.com/pact-foundation/pact-php/blob/3c234e794ac8786bed559264aeaf840f1deb8ff5/src/PhpPact/Standalone/MockService/Service/MockServerHttpService.php#L150

This is called natively by the Listener: https://github.com/pact-foundation/pact-php/blob/3c234e794ac8786bed559264aeaf840f1deb8ff5/src/PhpPact/Consumer/Listener/PactTestListener.php#L91

And is called in the examples I posted above.   Again, I cannot replicate this issue.  @DerManoMann , can you fork the examples above and replicate the issue?

**Comment by cfmack** [comment]
Yes, if you do not use the PHP Listener, you do need to explicitly call

```
$httpService = new MockServerHttpService(new GuzzleClient(), $serverDetails['config']);
$httpService->verifyInteractions();
$json = $httpService->getPactJson(); 
```

I suppose we would wrap this function in a WritePact() function.  Something like

```
public function WritePact() {
     $this->getPactJson();
}
```

It is certainly possible that it is sending a different signal to shutdown.  I removed the line from my example 3:
https://github.com/cfmack/pact-php-example/blob/4611bfc5462142221a3d8167d7ba7af890384058/example-three-no-listener/test/ExampleThreeMeetupAPIClientTest.php#L52

Lo and behold, no file was written!  I think that is the bug/change that we can track down.   

As far as the debug output goes, there is always a balance on logging packages inside of libraries.   At minimum, the Ruby process can be passed a --log file location and a --log-level.   These can be found in your local install of vendor/pact-foundation/pact/README.md   I can open another issue for that.

**Comment by cfmack** [comment]
@cirnatdan ,

Any idea on why this was `kill -9`?   
https://github.com/pact-foundation/pact-php/blob/3c234e794ac8786bed559264aeaf840f1deb8ff5/src/PhpPact/Standalone/Runner/ProcessRunner.php#L175

When I remove it, the Ruby server successfully shuts down.  `kill ` seems to work just fine.  Is there a use case that I am not thinking of?

**Comment by DerManoMann** [comment]
Nice one! I am running CentOS 7.
Not sure if the listener really makes the difference. More like shutting down the server properly:)
Can't remember if Windows supports the kill level at all, so maybe this is a fundamental difference that should be documented.
Anyway, glad we are finally getting somewhere :)

**Comment by cfmack** [comment]
I took an early stab: https://github.com/pact-foundation/pact-php/commit/b5207228e94ab83ed1eb70c537f869c21fcd63d2

I'm going to bed as I wasn't able to get a new test working on this yet.

**Comment by DerManoMann** [comment]
Adding log settings support is great.

Personally I also wouldn't mind an explicit method to trigger the writing of JSON via an endpoint. Adding that to MockServerHttpService would be simple enough.

**Comment by bethesque** [comment]
Windows does not easily support an elegant kill. I tried to bake that into the ruby version so that all the languages would have it, but it was nigh on impossible. Bloody windows!

**Comment by DerManoMann** [comment]
Maybe another reason to explicitly do it outside the shutdown?

**Comment by bethesque** [comment]
Yes, a fair point.
