### ISSUE TITLE
PhpPact\Standalone\Runner\ProcessRunner\setStderr() method issue

### ISSUE THREAD

**Issue by jwangmk** [pact-foundation/pact-php#110]
When I run provider verification, the following error occurred,
TypeError: Return value of PhpPact\Standalone\Runner\ProcessRunner::getStderr() must be of the type string, null returned

If I change the return type of the method from "string" to "? string" , it works fine. 

    /**
     * @return string
     */
    public function getStderr():  string    => ? string
    {
        return $this->stderr;
    }

Should I change the code in this way or something else I should know.
I appreciate any help, thank you!

Jing

**Comment by cfmack** [comment]
I can replicate this issue and I think this is working as designed.   Stderr is only set if an exception is thrown via std err.   We could add a ?string to the process to show that NULL is returned.  This is apparent because no exception was thrown.  Thoughts?

```         
$p = new ProcessRunner('ls', ['-alt']);
            $p->runBlocking();

            $exitCode = $p->getExitCode();
            $this->assertEquals($exitCode, 0, 'Expect the exit code to be 0');
            $this->assertTrue((\stripos($p->getOutput(), 'total') !== false), "Expect 'total' to be in the output");

            // try an app that does not exists
            $p = new ProcessRunner('failedApp', ['']);

            try {
                $p->runBlocking();
            } catch (\Exception $e) {
            }

            $exitCode = $p->getExitCode();
            $this->assertNotEquals($exitCode, 0, 'Expect the exit code to be non-zero: ' . $exitCode);
            $this->assertTrue((\stripos($p->getStderr(), 'failedApp') !== false), "Expect 'failedApp' to be in the stderr");

```

**Comment by cfmack** [comment]
Today I learned, kill does not provide the exit code of the killing process.   Still investigating.

https://stackoverflow.com/questions/8256511/linux-get-the-exit-code-from-the-kill-command

**Comment by jwangmk** [comment]
Instead of running Verify->verify(), initialize a processRunner and execute runBlocking() directly in the verification process, I have to write many lines of code to prepare the parameters as below, actually it works. 

However we can use only one statement ` $verifier->verify('ConsumerApp') `  to do the same job if we add a ? string to the process to show that NULL is returned.

        try {
            $verifier = new Verifier($config);

            /**
             * Start for the replacement of $verifier->verify('ConsumerApp');
             */
            //$verifier->verify('ConsumerApp');

            /**
             * To avoid ProcessRunner->getStderr() error,
             * Initialize processRunner and execute runBlocking() directly,
             * instead of run Verify->verify().
             */
            //$path = "pacts/provider/ProviderApi/consumer/ConsumerApp/latest/";

            /**
             * If do not set tag or version, will verify the latest pact file.
             */
            $path = "pacts/provider/{$config->getProviderName()}/consumer/ConsumerApp/";
            $tag = null;
            //$consumerVersion = '2.0.0';
            $consumerVersion = null;

            /**
             * Possible to set either Tag or Version
             */
            if ($tag) {
                $path .= "latest/{$tag}/";
            } elseif ($consumerVersion) {
                $path .= "version/{$consumerVersion}/";
            } else {
                $path .= 'latest/';
            }

            $uri = $config->getBrokerUri()->withPath($path);

            $arguments = \array_merge([$uri->__toString()], $verifier->getArguments());

            $installManager = new InstallManager();

            $scripts = $installManager->install();

            $processRunner = new ProcessRunner($scripts->getProviderVerifier(), $arguments);

            $processRunner->runBlocking();

            //$exitCode = $processRunner->getExitCode();

            /**
             * End of the replacement of $verifier->verify('PCAdminApi');
             */
        } catch (\Exception $ex) {
            $hasException = true;
            $errorMessage = $ex->getMessage();
        }

**Comment by cfmack** [comment]
Yes, it was an obvious change.  I was struggling with the appropriate tests on Windows.   It should be on version 5.0.3
