### ISSUE TITLE
private property: "exitCode" in PhpPact\Standalone\Runner\ProcessRunner  issue

### ISSUE THREAD

**Issue by jwangmk** [pact-foundation/pact-php#111]
I would like to know the Pact verification result without checking files on the broker server.
Is there any way to get the result from PHPUnit output? 

In the class PhpPact\Standalone\Runner\ProcessRunner,
I saw exitCode was set by the method setExitCode(), but the exitCode was not passed to VerifierProcess class.

Here is the code in my PactVerifyTest.php, 

    $verifier = new Verifier($config);
    $verifier->verify('ConsumerAdminApi');

I hope I can check the exitCode after verification as below, 
   
    $verifier = new Verifier($config);
    $verifier->verify('ConsumerAdminApi');
    $verifier->getExitCode();

Due to the calling procedure, 
Verifier class calls VerifierProcess class, then VerifierProcess class calls ProcessRunner class,  
so that I have to write two methods setExitCode() and getExitCode() into Verifier Class and VerifierProcess Class, therefore I can get the exitCode in my PactVerifyTest.php.

Could you please check if you have any better way to check the exitCode (verification result), thank you.

**Comment by jwangmk** [comment]
Hello,

After Merging pull request #112 from pact-foundation/graceful-exit, 
it's possible to use try/catch to catch the exception, therefore I can know the provider verification result from PhpUnit output without checking the exitCode any more.

Thanks!

**Comment by cfmack** [comment]
I am also adding nullable to the return, I think that makes the most sense.

**Comment by jwangmk** [comment]
@cfmack Thank you!

Yes, it does throw an exception right now. I don't need to check the exit code any more.

It did not throw the exception because I did not have this commit [https://github.com/pact-foundation/pact-php/pull/112/commits/334a03a875278d182bd57ab25223dd1f5abf9fe0](https://github.com/pact-foundation/pact-php/pull/112/commits/334a03a875278d182bd57ab25223dd1f5abf9fe0) in the code before.

Thanks again.
