### ISSUE TITLE
Is it possible to use Matcher for response Header?

### ISSUE THREAD

**Issue by jwangmk** [pact-foundation/pact-php#116]
Hello,

We can use MATCHER to set response Body for loose comparison, 
Is it possible to use MATCHER to set response Header? 
For example, may I use regular expression to set  the value for Content-Type in the Header, instead of the exact value  'application/json'.

$matcher = new Matcher();

$response = new ProviderResponse();
$response
    ->setStatus(200)
    ->addHeader('Content-Type', _'application/json'_)
    ->setBody([
        'message' => **$matcher->regex('Hello, Bob', '(Hello, )[A-Za-z]')**
    ]);

Thanks in advance.

**Comment by cfmack** [comment]
Yes, I believe so.  I changed the [consumer example](https://github.com/pact-foundation/pact-php/blob/master/example/tests/Consumer/Service/ConsumerServiceHelloTest.php) to do this.    Try this and see if your Provider test works.

```
        // Create your expected response from the provider.
        $response = new ProviderResponse();
        $response
            ->setStatus(200)
            ->setHeaders([
                'new-header-message' => $matcher->term('hello-bob', '(hello-)[A-Za-z]'),
                'Content-Type' => 'application/json;charset=utf-8'
            ])
            ->setBody([
                'message' => $matcher->term('Hello, Bob', '(Hello, )[A-Za-z]')
            ]);
```

**Comment by jwangmk** [comment]
thanks a lot :D
