### ISSUE TITLE
Unable to build interaction without given

### ISSUE THREAD

**Issue by arun290636** [pact-foundation/pact-php#117]
when i build interaction as below 👍 $config = new MockServerEnvConfig();
        $builder = new InteractionBuilder($config);
        $builder
            ->uponReceiving('A get request to /hello/{name}')
            ->with($request)
            ->willRespondWith($response); // This has to be last. This is what makes an API request to the Mock Server to set the interaction.

Below error is thrown by phpPact:
TypeError: Return value of PhpPact\Consumer\Model\Interaction::getProviderState() must be of the type string, null returned

**Comment by cfmack** [comment]
Doing some quick research, it appears that providerState/given() is optional on other languages.  Here is the ruby example: https://github.com/pact-foundation/pact-ruby-e2e-example/blob/master/consumer/spec/pacts/foo-bar.json

This appears to be a bug.

**Comment by cfmack** [comment]
Try now, pulling from dev-master.   If that works, I can make a quick tag.

**Comment by mefellows** [comment]
Thanks, yes it is definitely an optional field.
