### ISSUE TITLE
Follow PSR-2 codingsstandards

### ISSUE THREAD

**Issue by ruudk** [pact-foundation/pact-php#12]
Sorry to say, but on some places, the code is really a mess. 

It would be great if we could follow the [PSR-2 standard](http://www.php-fig.org/psr/psr-2/).

We can even automatically fix the current code with https://github.com/friendsofphp/php-cs-fixer

If no big refactors are happening right now, I can try to run it and create a PR for it? It needs to be merged fast because it will be annoying for others that are working on improvements and having to rebase.

**Comment by mattermack** [comment]
I'm game.  I have a separate request to follow PSR-3 but no pull requests yet.  I do not have major fixes in the works yet.  I'm starting to work on v2.  That said, with such a large refactor as you mentioned, we really need AppVeyor running on pull requests

**Comment by ruudk** [comment]
BTW, Why are you using AppVeyor? If it's hard to set up on pull requests we could use Travis?

**Comment by mattermack** [comment]
As I mentioned, Windows is my primary concern and AppVeyor does a good job at that.   AppVeyor should be setup appropriately now.

**Comment by mattermack** [comment]
I'm going to see if I can pull this off today.

**Comment by mattermack** [comment]
This was a great idea.  I plugged php-cs-fixer into AppVeyor.

Merged to master but not re-tagged

**Comment by ruudk** [comment]
Nice!
