### ISSUE TITLE
MockServerHttpService::verifyInteractions Not handling ServerException

### ISSUE THREAD

**Issue by braddle** [pact-foundation/pact-php#120]
Im not sure whether the bug is here or in the Mock Server implementation.

The bug occurs when MockServerHttpService::verifyInteractions calls GET /interactions/verification the function expects a HTTP 200 response.
 
This is how the test are setup 
https://github.com/pact-foundation/pact-php/blob/d419cf4020f1b1063d7e2d757aba5c4c126b50f3/tests/PhpPact/Standalone/MockServer/Service/MockServerHttpServiceTest.php#L98

The bug occurs because the mock server actually returns a HTTP 500 which causes Guzzle to throw a  ServerException.

If you catch the exception and return false the bug is fixed.

**Comment by braddle** [comment]
I have opened a PR assuming the bug is in the MockServerHttpService::verifyInteractions and not the mock server.

https://github.com/pact-foundation/pact-php/pull/121

**Comment by cfmack** [comment]
@braddle ,  I have been unable to look at this yet.   Hopefully I can this weekend.
