### ISSUE TITLE
PactVerifyTest returns exit code 1

### ISSUE THREAD

**Issue by Benxxen** [pact-foundation/pact-php#122]
Hello guys,

i´m new in this whole pact-php stuff and i´ve started to run the  examples of this project and it fails because of a non-zero exit code: 1. I'm not getting any further information about the error. So i tried to write my own example and I'm getting it done to register and test the interactions, but I'm running into the same error again and again. Do you guys have any idea or information of how i can get more information out of it?

**Comment by cfmack** [comment]
Are you running on Windows?   There were some cases where this proved difficult on Windows.  

Also, I think you may be able to get more information if issue Pass Ruby server log configurations #109 was implemented.  Hopefully, I can get to it soon but have been rather busy.   PRs are always welcome.

**Comment by Benxxen** [comment]
No I'm running it on OS X and if i run the examples it shows the following output. For me it seems like the test was successful so what does the failure log output means?

[2019-05-22 09:30:50] server.info: Listening on http://[::1]:7201/ [] []
[2019-05-22 09:30:53] server.debug: Accept ::1:50766 on ::1:7201 #752 [] []
[2019-05-22 09:30:53] server.debug: POST http://localhost:7201/ HTTP/1.1 @ ::1:50766 [] []
[2019-05-22 09:30:53] server.debug: Close ::1:50766 #752 [] []
[2019-05-22 09:30:53] server.debug: Accept ::1:50767 on ::1:7201 #772 [] []
[2019-05-22 09:30:53] server.debug: POST http://localhost:7201/ HTTP/1.1 @ ::1:50767 [] []
[2019-05-22 09:30:53] server.debug: Close ::1:50767 #772 [] []
.             53 / 53 (100%)INFO: Reading pact at /Users/benjamin.keidel/workspace/pact-php/example/tests/MessageProvider/../../output/test_consumer-test_provider.json

Verifying a pact between test_consumer and test_provider
  Given a hello message
    an alligator named Mary exists
      has matching content
  Given You can hear happiness staggering on down the street
    footprints dressed in red
      has matching content

2 interactions, 0 failures



Time: 26.57 seconds, Memory: 10.00 MB

There was 1 error:

1) Provider\PactVerifyTest::testPactVerifyConsumer
Exception: PactPHP Process returned non-zero exit code: 1

**Comment by Benxxen** [comment]
I´ve found the issue inside the pact files. The problem is the UTF-8 encoding which is used as the content-type header. So the content-types which were used and expected were not the same. I'm living in Germany so this could be reason for the encoding problem^^
