### ISSUE TITLE
Unstable test

### ISSUE THREAD

**Issue by Thomblin** [pact-foundation/pact-php#124]
Even if my pull request was green, the merge into master left one test failing.

> Test 'PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess' started
> [2019-05-30 02:54:05] server.DEBUG: Process command: dir  [] []
> [2019-05-30 02:54:05] server.DEBUG: Exit code: 0 [] []
> [2019-05-30 02:54:05] server.DEBUG: Process command: dir failed.xx [] []
> [2019-05-30 02:54:05] server.DEBUG: Exit code: 2 [] []
> Test 'PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess' ended
> 
> There was 1 failure:
> 
> 1) PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess
> Expect 'failed.xx' to be in the stderr
> Failed asserting that false is true.
> C:\projects\pact-php\tests\PhpPact\Standalone\Runner\ProcessRunnerTest.php:47

Any ideas how to fix it?

**Comment by mattermack** [comment]
Merged based on your refactor

**Comment by mattermack** [comment]
Reopenning as Windows continues to appear unstable:
Reason 1: https://ci.appveyor.com/project/mattermack/pact-php/builds/25020714
Reason 2: https://ci.appveyor.com/project/mattermack/pact-php/builds/25020861
Passing (w/o changes): https://ci.appveyor.com/project/mattermack/pact-php/builds/25020935

**Comment by Thomblin** [comment]
That is strange. I'll take a look at it

**Comment by Thomblin** [comment]
I created a pull request
