### ISSUE TITLE
Connect Appveyor with Github to automatically test PR's

### ISSUE THREAD

**Issue by ruudk** [pact-foundation/pact-php#13]
Would be great if all PR's could be automatically tested using Appveyor. 

My #9 PR is not being tested atm.

**Comment by mattermack** [comment]
It should.  I messed with it for about an hour and a half.   I thought I had it.   Do you have experience with AppVeyor

**Comment by mattermack** [comment]
Try again.

**Comment by mattermack** [comment]
I had a bug in the appveyor.yml.   Should be good to go after testing.  See https://github.com/pact-foundation/pact-php/pull/15
