### ISSUE TITLE
Tag 5.0.5

### ISSUE THREAD

**Issue by Thomblin** [pact-foundation/pact-php#133]
Could you release version 5.0.5? I can support you if there's something to do first

**Comment by cfmack** [comment]
Just committed.   The list on the issue around Pact v3 is interesting.

**Comment by cfmack** [comment]
Adding additional examples would also be great

**Comment by Thomblin** [comment]
@cfmack  Indeed. However the ruby standalone does not support that stuff yet, and I did not really understand how I could add new matchers there for example

**Comment by mattermack** [comment]
You're right!

**Comment by Thomblin** [comment]
@cfmack packagist does not provide version 5.0.5. Do I miss something here?

https://packagist.org/packages/pact-foundation/pact-php
