### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by Thomblin** [pact-foundation/pact-php#134]
The last merge into master failed. I was not able to reproduce or understand the error. Any thoughts?

references:
https://ci.appveyor.com/project/mattermack/pact-php
https://travis-ci.org/pact-foundation/pact-php/jobs/552515172

**Comment by peter279k** [comment]
The possible error messages are as follows:

```
Fatal error: Uncaught InvalidArgumentException: Header value must be a string or numeric but boolean provided. in /home/travis/build/pact-foundation/pact-php/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 190
InvalidArgumentException: Header value must be a string or numeric but boolean provided. in /home/travis/build/pact-foundation/pact-php/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 190
```

It looks like the Client throws request exception with Guzzle HTTP client.

**Comment by Thomblin** [comment]
@peter279k Are you able to reproduce the error?

**Comment by mattermack** [comment]
I was unable to replicate the error.   I ran that build through Travis and Appveyor.  Travis failed on that exact spot.  Thinking that it had to do with a "composer dependency high|low" library, I ran it yet again ... and it passed.  Now it seems I lost the original failure

**Comment by peter279k** [comment]
I also have the same situation that @mattermack mentions.

After I run the Travis CI build again, the CI build is successful.

I guess this is the temporary error in Travis CI build.

**Comment by Thomblin** [comment]
I would agree. My local and travis builds passed as well. Thank you for your support

**Comment by frastel** [comment]
Issue could be closed then.

**Comment by cfmack** [comment]
Closing as I am simply doing some issue clean up
