### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Akinah** [pact-foundation/pact-php#140]
Could we get a new release?
I'm getting the following error in my Laravel 5.6 project that I believe will be fixed by PR #136.
```Error: Call to undefined method Monolog\Logger::addInfo()```

**Comment by frastel** [comment]
Workaround: Pin Monolog to v1.x as pact-php is currently not compatible to monolog v2.

```
composer require monolog/monolog ^1.25
```

**Comment by cfmack** [comment]
I can make a new version this week.   There's an open PR that I am looking to pull in given time.

**Comment by cfmack** [comment]
I tagged 5.0.6
