### ISSUE TITLE
Pact-PHP <=9.x.x - Message Provider State Issues

### ISSUE THREAD

**Issue by cfmack** [pact-foundation/pact-php#146]
1. Enable filtering of callback descriptions in MessageBuilder.php::Verify().  It currently cycles through all callbacks
1. Require the provider states into the callbacks for MessageVerifier.php::verifyAction().  It currently does not pass provider states to the callback.  Thus, provider states are ignored at the exact moment

Both of these were previous and latent bugs

**Comment by YOU54F** [comment]
Assumed resolved in 10.x which utilises the pact_reference core. If not, new defects should be raised.

if anyone wishes to backport fixes to the release/9.x, we are willing to accept if they are covered by tests 👍🏾
