### ISSUE TITLE
Remote pact mock server

### ISSUE THREAD

**Issue by catalinzanfir-am** [pact-foundation/pact-php#152]
Hello, 
I have microservices that are running in a slim php image inside docker, therefore I am unable to install ruby on them, so my tests fail to connect to the internal mock pact server, since ruby isn't(and can't be) installed.

- is it possible to run the pact tests in a docker image? If yes, how am i supposed to do it?

What are my options in order to have a integrated running pact environment within kubernetes?
Thanks.

**Comment by mefellows** [comment]
This should help https://docs.pact.io/docker

Also, you don't need to install Ruby. The standalone package it downloads already includes a Ruby runtime.

**Comment by bethesque** [comment]
The problem is, Pact PHP might not support providing a standalone mock server. The Ruby impl does. You might need to raise a feature request.

**Comment by mefellows** [comment]
I guess this can be that feature request.

@catalinzanfir-am is your problem that you can't run any pact tests within a Docker environment? Or is it that you want to deploy the pact mock server on a separate docker container to the PHP service and that Pact PHP doesn't support that model?

(or something else).

**Comment by catalinzanfir-am** [comment]
Hello @mefellows,

Let me describe once again my situation: 
I have the microservices running in docker orchestrated by kubernetes. When i run the pact tests from inside docker, 
- the consumer tests report that: 
-- `Fatal error:  Uncaught PhpPact\Standalone\Exception\HealthCheckFailedException: Failed to make connection to Mock Server in 10 attempts. in /vendor/pact-foundation/pact-php/src/PhpPact/Standalone/MockService/MockServer.php:153`
- the provider tests report that: 
-- `console.error: err > /var/www/vendor/pact-foundation/pact-php/pact/lib/ruby/bin/ruby: line 11: /var/www/vendor/pact-foundation/pact-php/pact/lib/ruby/bin.real/ruby: No such file or directory`
-- `Tests\Pact\Provider\ProviderTest::testCustomerProvider
Exception: PactPHP Process returned non-zero exit code: 127`
-- both files exist

Well.. I'm not really sure what's happening. I'm guessing the ruby exec isnt able to start due to something missing from my docker images.. (basically the images only have php and nginx)

Back to your questions,
Q: is your problem that you can't run any pact tests within a Docker environment
A: yes
 
but most importantly i wanted to obtain this:
`I want to deploy the pact mock server on a separate docker container to the PHP service.` so i could keep my docker images unchanged, so i could the same one mock server per cluster , as i do with the pact broker.

thank you

**Comment by mefellows** [comment]
OK, as for running the mock service in docker - please see my comment above. In fact, we [already have a docker container you can use](https://hub.docker.com/r/pactfoundation/pact-cli). You can test this in isolation of the second point.

You'll need to verify this yourself, but looking at the way the docs specify it, you could just _not_ start/stop the server. This is more or less consistent with the way we allow it in Pact JS:

```
<?php
    use PhpPact\Standalone\MockService\MockServer;
    use PhpPact\Standalone\MockService\MockServerConfig;

    // Create your basic configuration. The host and port will need to match
    // whatever your Http Service will be using to access the providers data.
    $config = new MockServerConfig();
    $config->setHost('localhost');
    $config->setPort(7200);
    $config->setConsumer('someConsumer');
    $config->setProvider('someProvider');
    $config->setCors(true);

    // Instantiate the mock server object with the config. This can be any
    // instance of MockServerConfigInterface.
    $server = new MockServer($config);

    // Create the process -> Don't call this!
    $server->start();

    // Stop the process -> Don't call this!
    $server->stop();
```

There may be some state within the `MockServer` that won't let you do things if not started, so there may still be a need to raise a feature request.

**Comment by catalinzanfir-am** [comment]
Alright, I will test the consumer tests with [this docker image](https://hub.docker.com/r/pactfoundation/pact-cli) using:
```
docker run -dit \
  --rm \
  --name pact-mock-service \
  -p 1234:1234 \
  -v ${HOST_PACT_DIRECTORY}:/tmp/pacts \
  pactfoundation/pact-cli:latest \
  mock-service \
  -p 1234 \
  --host 0.0.0.0 \
  --pact-dir /tmp/pacts
```
.

However, i thought, since the following variables are available in the phpunit.xml file:
```
<env name="PACT_MOCK_SERVER_HOST" value="localhost"/>
<env name="PACT_MOCK_SERVER_PORT" value="7201"/>
```
you could just provide an url to a pact mock server (one that is hosted on in docker, started, and listening to inputs)

**Comment by mefellows** [comment]
I don't know much about that, but give it a go!

**Comment by catalinzanfir-am** [comment]
Hello again.
I've managed to run the pact-mock-server with:

```
docker run -dit \
  --rm \
  --name pact-mock-service \
  -p 1234:1234 \
  -v /Users/catalinzanfir-am/work/app-name/pact/output:/example/output \
  pactfoundation/pact-cli:latest \
  mock-service \
  --port 1234 \
  --host 0.0.0.0 \
  --pact-file-write-mode=overwrite \
  --consumer=android-consumer \
  --provider=ms-provider \
  --pact-dir /example/output \
  --log /example/output/log.log
```
So i guess it solves the issue, but it's a bit tricky to use because:
- you have to start the mock server before your tests, because the test doesn't know how to start the remote docker vm (obviously)
-  and because you start it manually, you can't rely on the parameters set in phpunit.xml and you have to set the parameters as in the example above 

@mefellows / @bethesque i have some other questions, but i don't wanna spam the issues tab. are you interested to discuss on some platform of your choice(slack, discord, skype etc)?

**Comment by mefellows** [comment]
Good to hear it works - that all sounds about right to me.

Sure, please join us at slack.pact.io and chat in the #pact-php channel.

**Comment by YOU54F** [comment]
The alpine container needed extra deps with a ruby runtime

https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker

The pact mock server written in rust is published to docker

https://hub.docker.com/r/pactfoundation/pact-ref-mock-server

it is now a single executable built with rust, statically linked to musl so will run on glibc or musl based hosts.

the images are multi-arch and also published to ghcr

a reference verifier exists published to dockerhub too

https://hub.docker.com/r/pactfoundation/pact-ref-verifier
