### ISSUE TITLE
Unable to create 4XX contracts

### ISSUE THREAD

**Issue by catalinzanfir-am** [pact-foundation/pact-php#153]
Hello,

I am unable to create consumer tests that end up in (expected) 4XX response codes.

Is this by design of the pact framework? or it's just an 'error' from the pact-php wrapper/implementation?

below is the (relevant) backtrace / my debugging:

```
1) Tests\Pact\Consumer\EmailIsRegisteredTest::testEmailIsNotRegistered
GuzzleHttp\Exception\ClientException: Client error: `POST http://localhost:7201/api/users/email-is-available` resulted in a `404 Not Found` response: /* the 404 Not Found is the correct and the expected response code */
{"error":{"code":404,"message":"not found","errors":["not found"],"error_code":null}} /* this is the actual and correct response */

/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
/vendor/guzzlehttp/guzzle/src/Middleware.php:65
```

I've temporarily modified the class `Middleware.php:65` from guzzle library this way, just to see what happens in pact

```
//if ($code < 400) {
  if ($code < 4000) {
       return $response;
  }
  throw RequestException::create($request, $response);
```
and it worked. the contract was created, and i was able to verify it.

**Comment by mefellows** [comment]
I can't speak for the PHP implementation details, but I can say for sure that _all_ http status codes should be verifiable via pact - and `400` is a very common use case. So, that sounds like a bug to me!

**Comment by mefellows** [comment]
Could you please whip us up a reproducable example? Is it possible that your client code (i.e. the code under test) is the issue? Can you show that the issue is definitely within Pact PHP and not within your client? Are you using Guzzle as your HTTP client or is that in Pact PHP?

**Comment by catalinzanfir-am** [comment]
here's a repository containing a reproducible example: https://github.com/catalinzanfir-am/pact-404
I've also added the cli output in the readme file.

to reproduce
- run `composer install`
- run `./vendor/bin/phpunit -c tests/pact/consumer/phpunit.xml`

**Comment by mefellows** [comment]
Thanks for the repro, that's really nice!

Actually, as expected, the Guzzle client throws an error for status codes > 400 (seehttp://docs.guzzlephp.org/en/stable/request-options.html#http-errors )

Change your code to do this, and it passes:
```
$client->get($url, ['http_errors' => false]);
```
