### ISSUE TITLE
Question about allowExtraObjectKeys

### ISSUE THREAD

**Issue by ruudk** [pact-foundation/pact-php#16]
I'm finishing up my PR (takes a bit of time to work out the issue) and I stumbled on this:
https://github.com/pact-foundation/pact-php/blob/c9ac394e63277fc5007453a9c0da16b51a3e48bd/src/Mocks/MockHttpService/Matchers/JsonHttpBodyMatcher.php#L71

Why does it pass `false` to `ProcessResults` when:
https://github.com/pact-foundation/pact-php/blob/c9ac394e63277fc5007453a9c0da16b51a3e48bd/src/Mocks/MockHttpService/Matchers/JsonHttpBodyMatcher.php#L55

**Comment by mattermack** [comment]
Pact handles Arrays differently.   By explicitly passing false in for arrays only, we can use the same JSON Diff library.  

See https://github.com/pact-foundation/pact-specification/tree/version-1.1
- Allow unexpected keys to be sent back in the body. See "Pact Specificaton Philosophy" in main README.
- Do not allow unexpected items in an array. Most parsing code will do a "for each" on an array, and if we expect one item, but receive two, we might not have exercised the correct code to handle that second item in our consumer tests.
