### ISSUE TITLE
Add support for consumer/provider names with a space.

### ISSUE THREAD

**Issue by siad007** [pact-foundation/pact-php#171]
As in the given snipped, it is not easy to pass a valid consumer/provider name with a space.
For example `--consumer=Foo Bar` is not possible:

https://github.com/pact-foundation/pact-php/blob/3a29da6a8af6d9ffc11e808fa5850a8e7d23aefa/src/PhpPact/Standalone/MockService/MockServer.php#L108-L109

Before encoding it by hand or with `rawurlencode`, to convert the spaces to `%20`, we should consider to `rawurlencode` or maybe better `escapeshellarg` ❓ it right at that place.

What do you think?

**Comment by bethesque** [comment]
escapeshellarg. Don't URL encode it - that's the job of the underlying HTTP client.
