### ISSUE TITLE
Chore: migrate away from TravisCI

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-php#183]
TravisCI (org) is dropping support for OSS builds at the end of this month, meaning they must be transferred to travis-ci.com, which uses a credit system. Builds may fail (and already are) if the number of credits is exhausted within the month.

We are recommending switching to GH Actions, but the choice of CI provider is up to the project maintainer.

See also:

https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/5

**Comment by frastel** [comment]
As I understand this post correctly https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing you have the possibility to increase the credit allotment by contacting their support.
So the project still could be build for free if the credit limit is set correctly. I could not estimate the amount of credits this project would need.

**Comment by mefellows** [comment]
Yes. We've reached out, but it remains to be seen how many credits we'll receive.

The credits are also applied at the org level, not repo. So that introduces another variable.

**Comment by cfmack** [comment]
I put in for some clean up actions
Add Github Actions badge to README #188
