### ISSUE TITLE
phpunit versions should be constrained through composer.json

### ISSUE THREAD

**Issue by ctrl-f5** [pact-foundation/pact-php#193]
phpunit should be moved from `require-dev`to `require` so this package can constrain which versions of phpunit it supports.

Currently the support is documented in the readme file, but one can install it with unsupported versions. by moving phpunit into `require` composer can check supported versions during install.

**Comment by YOU54F** [comment]
Completed by

 https://github.com/pact-foundation/pact-php/commit/7b50c96f820ed0f5cc422fb4c417a2df7b86f6d0
