### ISSUE TITLE
Pact-PHP <=9.x.x - setRequestFilter doesn't seem to append anything to the request

### ISSUE THREAD

**Issue by mattias-persson** [pact-foundation/pact-php#196]
Trying the setRequestFilter feature but it doesn't append any headers in the request. My test looks just like the example in the documentation:

```php
/** @test */
public function remarketed_orders()
{
    $config = new VerifierConfig();
    $config
        ->setProviderName('my-provider') // Providers name to fetch.
        ->setProviderVersion('1.0.0') // Providers version.
        ->setProviderBaseUrl(new Uri('my-url')) // URL of the Provider.
        ->setBrokerUri(new Uri('my-broker-uri')) // URL of the Pact Broker to publish results.
        ->setBrokerToken('my-token')
        ->setPublishResults(false) // Flag the verifier service to publish the results to the Pact Broker.
        ->setEnablePending(true) // Flag to enable pending pacts feature (check pact docs for further info)
        ->setIncludeWipPactSince('2020-01-30') //Start date of WIP Pacts (check pact docs for further info)
        ->setRequestFilter(
            function (RequestInterface $r) {
                return $r->withHeader('MY_SPECIAL_HEADER', 'my special value');
            }
        );

    // Verify that all consumers of 'someProvider' are valid.
    $verifier = new Verifier($config);
    $verifier->verify('my-consumer');

    // This will not be reached if the PACT verifier throws an error, otherwise it was successful.
    $this->assertTrue(true, 'Pact Verification has failed.');
}
```
I've been digging around the code a bit and can't see that the `verify` method actually adds any request filters. I've also tried the `verify` method and I've tried using `withAddedHeader` instead of `withHeader`. Nothing seems to work.

@siad007 I saw that you built the feature initially, maybe you have any clues?

**Comment by siad007** [comment]
@mattias-persson I will have a look ASAP - hopefully today in the evening!

**Comment by siad007** [comment]
@mattias-persson after some investigation on your problem, it seems related to the guzzle dependency.
I just found a very similar issue on their bug tracker [here](https://github.com/guzzle/guzzle/issues/2858)
pact-php does not make any magic here, just pass the callback to the guzzle handler stack. Will also have a look in the guzzle code, if I have some more time in the next days.

**Comment by mattias-persson** [comment]
@siad007 Appreciate it!

**Comment by ALTELMA** [comment]
Any updates on this issue? I facing the same problem on this.

**Comment by ALTELMA** [comment]
@cfmack Thanks for a quick reply. That's means requestFilter never work anymore, right? In my opinion should remove from an example.

**Comment by YOU54F** [comment]
This feature was removed in the v10.x release using the pact_ffi library.

If any readers wish to have this feature in the reworked pact-php library, please feel free to raise a pull request with appropriate tests.

Thanks
