### ISSUE TITLE
Get CI working with Github Actions

### ISSUE THREAD

**Issue by cfmack** [pact-foundation/pact-php#203]
Get Windows working php ini working, new lint checker, and PHP 7.3, 7.4 and 8.0

**Comment by cfmack** [comment]
A new version tag is not intended until CI is passing and working.

**Comment by cfmack** [comment]
Thanks to the work of  @Sertion in fix: Fixing pipeline issues with PHP 8 compatibility #205 , CI is now working again with PHP 8

**Comment by Sertion** [comment]
No problem.

As far as I can tell [all three PHP versions are succeeding on the merge commit](https://github.com/pact-foundation/pact-php/runs/2991829515?check_suite_focus=true).
