### ISSUE TITLE
Add support for consumer version selectors for deployed and released versions

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-php#206]
Please add support for the following keys to be used in the consumer version selectors when fetching pacts for verification:

```
{ "deployedOrReleased": true }

{ "deployed": true }

{ "released": true }

{ "environment": "<env name>" }

{ "consumer": "<name>" } // this may already be supported, please add it if not
```

These keys can be used in various combinations ( eg. `{ "environment": "prod", released: true, consumer: "Foo" }` ). Please allow any combination of keys, and do not validate them locally, as the validation rules can change over time as support is added for new selectors - just ensure that any errors returned from the API are displayed clearly to the user.

See https://github.com/pact-foundation/pact_broker/blob/master/lib/pact_broker/doc/views/provider-pacts-for-verification.markdown for the usage docs of each selector.

As more selectors will be added over time, it's my preference that the consumer version selectors are not strongly typed, and are just passed through straight from the configuration object to the API, so that we don't have to make code changes to the Pact clients each time we add new selectors. (eg. there will be new selectors coming for branch support very soon). I understand that this is not compatible with the idioms of every Pact client language however, so do whatever you need to do to make the new selectors work elegantly within your language.

Please update https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/ for your language once the selectors have been released.

**Comment by bethesque** [comment]
What is the status on this please? I'm updating the docs with a section on which languages/versions support the selector, so people know if they can use it or not.

**Comment by YOU54F** [comment]
arbitrary json can be provided in 9.x.x for the selectors

feature was introduced in https://github.com/pact-foundation/pact-php/pull/213

@tienvx has implemented in the v10.x alpha release, and main branch to also validate the json provided are valid selectors. 

docs

https://github.com/pact-foundation/pact-php/blob/master/docs/provider.md#verify-from-pact-broker

and in code, here is a test showing named selectors, and json selectors being passed.

https://github.com/pact-foundation/pact-php/blob/912b5f4831439f392de6816bfa969e728c0ad52d/tests/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectorsTest.php#L15-L17

Might not meet the brief on this

> Please allow any combination of keys, and do not validate them locally, as the validation rules can change over time as support is added for new selectors - just ensure that any errors returned from the API are displayed clearly to the user.

As I am aware the pact broker itself will return an error message stating that a particular selector isn't valid, so this may be a want for a future enhancement.

Going to close as implemented, and will note that the consumer version selectors page, could do with some examples for PHP :)

https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors#code-examples-with-branches
