### ISSUE TITLE
shell script use bash instead of sh

### ISSUE THREAD

**Issue by ctrl-f5** [pact-foundation/pact-php#216]
all shell scripts use `bash` instead of `sh` which makes them less portable. (eg php alpine does not have bash)

Do these scripts really need bash specific features?

**Comment by bethesque** [comment]
Is this the scripts inside of the pact ruby standalone?

**Comment by ctrl-f5** [comment]
https://github.com/pact-foundation/pact-php/search?q=%22env+bash%22

**Comment by bethesque** [comment]
Feel free to open a PR to convert them to sh.
