### ISSUE TITLE
1.1.0 composer requirements broken

### ISSUE THREAD

**Issue by c0ntax** [pact-foundation/pact-php#22]
Attempting to require mattersight/phppact:1.1.0 results in the following composer error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mattersight/phppact ^1.1 -> satisfiable by mattersight/phppact[1.1.0].
    - mattersight/phppact 1.1.0 requires lukascivil/treewalker dev-bugfix-branch -> no matching package found.
```

I'm assuming that the dev-bugfix-branch has been merged and deleted?

**Comment by c0ntax** [comment]
Ignore this. I did not RTFM! ;-)

**Comment by mattermack** [comment]
@c0ntax,
 
That dependency should also been fixed on dev-master.   I appreciate reading the release notes 👍 

As an fyi, if all goes well Php Pact 2.0.0 should be out in a few weeks, as Matchers are particularly helpful.
