### ISSUE TITLE
json_encode error on publishing

### ISSUE THREAD

**Issue by dkiselew** [pact-foundation/pact-php#24]
I've encountered an error (looks like a bug) when i'm trying to publish to pact broker like it stated in readme:
```
json_decode() expects parameter 1 to be string, object given

/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/vendor/mattersight/phppact/src/Mocks/MockHttpService/Models/ProviderServiceResponse.php:135
/vendor/mattersight/phppact/src/Mocks/MockHttpService/Models/ProviderServiceResponse.php:121
/vendor/mattersight/phppact/src/PactBrokerConnector.php:98
/vendor/mattersight/phppact/src/PactBrokerConnector.php:73
/vendor/mattersight/phppact/src/PactBrokerConnector.php:59
```
It does not depend on interactions. Could you please test it? Version 1.0.5

**Comment by mattermack** [comment]
It looks like you are going from PublishFile().   That means it is reading a JSON document on a local file system.   As I think it was alluded to in the README, you can publish from an ProviderServicePactFile, a JSON string, or a File.   Both PublishFile() and PublishJson() convert the input into a ProviderServicePactFile object.  Looking at the code, ProviderServicePactFile is then re-serialized into JSON to pas to PactBroker.   

In your case, it appears there is a error parsing your JSON into a ProviderServicePactFile object and then back into JSON.

**Comment by dkiselew** [comment]
Yes, i've tried to publish right from ProviderServicePactFile, like `$connector->Publish($this->pactFile, self::PACT_VERSION);` and it works correctly.

**Comment by dkiselew** [comment]
But still when publishing from a file with any content i get warning: `PHP Warning:  json_decode() expects parameter 1 to be string, object given in /Users/macbook/odesk/agency-settings-binder/vendor/mattersight/phppact/src/Mocks/MockHttpService/Models/ProviderServiceResponse.php on line 135`.

**Comment by bethesque** [comment]
You can use the pact-broker CLI that comes with the standalone executables here: 
https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.13.0#pact-broker

This is actually the preferred method of publishing, and I'd suggest that the php implementation wraps this command as it does the mock service commands. It means that all the logic it uses (tagging, merging, retries, basic auth) can be shared without having to duplicate code.
