### ISSUE TITLE
Error filtering ->verify($consumerName) after 7.1.2 update

### ISSUE THREAD

**Issue by rubengg86** [pact-foundation/pact-php#245]
After this change, https://github.com/pact-foundation/pact-php/commit/3915cde524346fd7207d20dad6cb2ce1268c831a, if we try to filter the verifier by consumer name using:

` $verifier = (new MessageVerifier($config))
            ->setCallbacks($callbacks)
            ->verify($this->consumerService);`

Doesn't work because is trying to verify with all pacts in the broker. If we rollback to 7.1.0 works fine

**Comment by cfmack** [comment]
@rubengg86, happy to take a PR.  Maybe from @WaylandAce

**Comment by WaylandAce** [comment]
I'll take a look

**Comment by YOU54F** [comment]
Looks at that commit, your issue sounds unrelated
