### ISSUE TITLE
Sunset PHP 7.3

### ISSUE THREAD

**Issue by Lewiscowles1986** [pact-foundation/pact-php#258]
Noticing the FFI PR from @tienvx and my rebase of that branch, both remove PHP 7.3 (makes sense, I don't think it supports FFI, and it's out of all support) https://github.com/pact-foundation/pact-php/pull/210 See: https://www.php.net/eol.php

In an effort to make that branch smaller, perhaps it is possible to cut a release that deprecates 7.3?

**Comment by cfmack** [comment]
Resolved
