### ISSUE TITLE
Future PHP

### ISSUE THREAD

**Issue by Lewiscowles1986** [pact-foundation/pact-php#259]
* Add support for PHP 8.1
* Question: Should PHP 8.2 (or whatever version is in development), be added to CI with failures allowed, to give visibility?

**Comment by cfmack** [comment]
Pull requests accepted, @MarcinBondaruk.

**Comment by cfmack** [comment]
I updated the base requirements in composer and github actions:
- CI Run: https://github.com/pact-foundation/pact-php/actions/runs/2769962320
- Branch: https://github.com/pact-foundation/pact-php/commits/feature/future-php

Looks like there's a phpunit uprev or some configuration needed.   I could use some assistance here to track all the dependencies down and get CI passing.  If you can help do that, gladly accepting PRs.

**Comment by cfmack** [comment]
Well hell, that was easier than expected.  New version coming

**Comment by cfmack** [comment]
Just pushed pact-php to 8.0.0 (technically waiting for CI to complete)
