### ISSUE TITLE
Newer syntax support

### ISSUE THREAD

**Issue by Lewiscowles1986** [pact-foundation/pact-php#260]
Assuming https://github.com/pact-foundation/pact-php/issues/258 can be agreed upon.
As seen in https://github.com/pact-foundation/pact-php/pull/210 php 7.4, 8& 8.1 can provide new syntax enhancements.

Technically 7.4 will be EOL very soon.

This is a placeholder discussion for discussing the use of more modern PHP syntax.

**Comment by tienvx** [comment]
I tried to use many PHP 8.1's features as possible listed at https://stitcher.io/blog/new-in-php-81

I think we can close this issue
