### ISSUE TITLE
Make examples end-to-end

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-php#269]
As pointed out in the discussion on #268, the examples rely on a consumer that might not be there.

@mefellows said:

> We have some examples that use Pactflow in other projects, but we always setup the consumer, publish the consumer and then verify the provider so we can be sure the data is there.

If we added or updated the examples so that the consumer was published before the provider then this issue would be avoided forever.

**Comment by YOU54F** [comment]
Tests are no longer reliant on an external pact broker.

A range of e2e examples have been created in the master branch for a suite of pact v4 enabled functionality thanks to @tienvx 

The pact compatibility suite leverages a dockerised pact broker
