### ISSUE TITLE
Support provider_state in PACT 1.1 jsons

### ISSUE THREAD

**Issue by mattermack** [pact-foundation/pact-php#27]
When reconstituting existing pacts that were created with `provider_state` as a node, instead of the 2.0 supported version of providerState, Pact should should still be able to reconstitute the object

**Comment by bethesque** [comment]
I'm a bit confused about why the php code cares about the pact format. All
the pact parsing and writing should be done by the underlying Ruby
implementation of the mock service and provider verifier. The content
should be abstracted from the php.

**Comment by mattermack** [comment]
Yes it should. It does not do that yet but it should

**Comment by bethesque** [comment]
How does pact php work?

**Comment by bethesque** [comment]
Oh, I see. You actually implemented the entire thing again. That's not exactly the recommended approach, as you would probably be aware by now. What are your plans for the future?

**Comment by bethesque** [comment]
Just an FYI, we're working on the other protocol support again now.

**Comment by mattermack** [comment]
@bethesque, that's great.  A co-working is writing a C# implementation of message support, which we can merge to support the ruby backend over time (like we are going to in Pact-PHP)
