### ISSUE TITLE
Install the pact binaries from composer instead of within the code

### ISSUE THREAD

**Issue by deanstalker** [pact-foundation/pact-php#276]
It would be preferable to see a function called from the `composer install/update` flow which downloads and populates the vendor/bin folder instead of managing the install within the runtime code.

The alternative is to configure the destination directory so we can bake the binaries into a docker image and use our paths instead of the hard-coded reference to the vendor folder. We don't allow web users to write to the vendor folder as a rule of thumb.

**Comment by YOU54F** [comment]
Both of those make sense, it was raised by another member and addressed by Tien in the upcoming pact-rust (FFI) backed version.

Would definitely consider an interim change against the ruby backed version, as a new PR 

https://github.com/pact-foundation/pact-ruby-standalone/pull/100

means that we open support up to additional platforms (arm64 linux and osx, and 32 bit windows, which was previously dropped in a traveling ruby update, but I've brought it back)

**Comment by YOU54F** [comment]
Ahh it's done, we just need to cut a new release, I've ran it through on my machine, that PR look good from @tienvx in #279

**Comment by YOU54F** [comment]
you can test this out by using `dev-master` in your composer.json
