### ISSUE TITLE
Mock HttpHeaderComparer breaks on PSR-7 header data

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#28]
Hi there,

Maybe I am doing something fundamentally wrong, but with both Guzzle and Windwalker PSR-7 requests the HttpHeaderComparer code breaks as it expects the header value to be a string rather than array.

**Comment by mattermack** [comment]
What version are of Pact-PHP are you using?
Can you post the Interaction?

**Comment by bethesque** [comment]
Hey Charles, would it be possible to put together a php e2e example like
the ruby one? I've found it invaluable in quickly recreating issues, and
allowing users to quickly recreate an issue without having to copy paste
all their private code.

**Comment by mattermack** [comment]
Most definitely.  I have [this example](https://github.com/mattermack/example-pact-php-consumer) from the Austin PHP Meetup a few months ago I can build on.   On a semi-related note, I've been flushing out some user stories and better examples for a different audience.  Tying it all together is a good idea.

**Comment by DerManoMann** [comment]
This is the code I've played around with. ````$reqest```` and ````$response```` are Guzzle6 PSR-7 objects.

I should add that I had a hard time figuring all this out, although I have to admit that I still struggle with the PACT concepts in general...

in particular the references to the pact file are quite unclear from the example - at least I didn't find anything obvious that tells me how to actually generate it (or how to change the base dir which defaults to a Windows path...)

Version is 2.0.2 which I installed following the documentation in the Readme.

````
          // =========== PACT ==================
          $pactConfig = new \PhpPact\PactConfig();
          $pactConfig->setPactDir(__DIR__);
          $builder = new \PhpPact\PactBuilder($pactConfig);
          $builder->serviceConsumer('api-client')
              ->hasPactWith('localhost')
          ;

          // map from psr-7
          $prequest = new \PhpPact\Mocks\MockHttpService\Models\ProviderServiceRequest(
              $request->getMethod(),
              $request->getUri()->getPath(),
              $request->getHeaders(),
              $request->getBody()->getContents()
          );
          $presponse = new \PhpPact\Mocks\MockHttpService\Models\ProviderServiceResponse(
              $response->getStatusCode(),
              $response->getHeaders(),
              $response->getBody()->getContents()
          );

          $mockService = $builder->getMockService();
          $pactFile = new \PhpPact\Mocks\MockHttpService\Models\ProviderServicePactFile();
          $pactFile->setProvider(new \PhpPact\Models\Pacticipant($builder->getProviderName()));
          $pactFile->setConsumer(new \PhpPact\Models\Pacticipant($builder->getConsumerName()));

          $mockService->given("Basic Get Request")
              ->uponReceiving("A GET request with a base / path and a content type of json")
              ->with($prequest)
              ->willRespondWith($presponse);

          // replay to capture ...
          $host = $mockService->getHost();
          $host->handle($request);

          $results = $mockService->verifyInteractions();
          $this->assertFalse($results->hasFailure());

          $builder->build();
````

**Comment by mattermack** [comment]
I think I see it.  I hope to look into this in the next couple of days.

From the [Guzzle documentation](http://docs.guzzlephp.org/en/stable/psr7.html), the headers are an array.   Looking at the Pact-PHP code, an array is certainly expected in a quick eyeballing.  Any chance you have a line number or stack trace?   I wonder if Guzzle does something odd that returns the first row in array if the array is size one or something like that.

**Comment by DerManoMann** [comment]
Happens in ````PhpPact\Mocks\MockHttpService\Comparers\HttpHeaderComparer```` around line 64 - that is the first line that treats the value as string.

Funny thing is Windwalker 3.2.7, which composer pulled, behaves the same (ie array instead of string value), so I do not know how any of the examples actually could work.

**Comment by bethesque** [comment]
An FYI, if you ever need to use multiple headers with the same name in pact, you'll need to `;` separate the value.

**Comment by mattermack** [comment]
@DerManoMann, I updated an example that uses Guzzle.  Next, I can try to determine how you are using it.  The example works as expected.

https://github.com/mattermack/example-pact-php-consumer/tree/master/example-guzzle

You will need to run example-api/run_server.sh to spin up the "API" to actually run example-guzzle/src/retrieve.php (unrelated to the Pact test)

**Comment by mattermack** [comment]
I can replicate this now.   First, I advice using the Mapper classes.   Even then, there is a different between the two libraries.   

`
// build the request
        $fullUrl =  self::TEST_URL . '/' . ExampleGuzzleMeetupApiClient::version . '/categories';
        $headers = array("Content-Type" => "application/json");
        $httpRequest = (new \GuzzleHttp\Psr7\Request( HttpVerb::GET , $fullUrl, $headers));
        
        // convert the request
        $requestMapper = new ProviderServiceRequestMapper();
        $request = $requestMapper->convert($httpRequest);
       
        // build the response
        $jsonBody = "{\"results\":[{\"name\":\"Games\",\"sort_name\":\"Games\",\"id\":11,\"shortname\":\"Games\"},{\"name\":\"Book Clubs\",\"sort_name\":\"Book Clubs\",\"id\":18,\"shortname\":\"Book Clubs\"}]}";
        $httpResponse = new \GuzzleHttp\Psr7\Response( '200' , $headers, $jsonBody);
        
        $responseMapper = new ProviderServiceResponseMapper();
        $response =  $responseMapper->convert($httpResponse);
`
I'll have to run some unit tests and see where things shake out.  In the mean time, you can use the examples in the aforementioned links

**Comment by mattermack** [comment]
I updated [this example](https://github.com/mattermack/example-pact-php-consumer/blob/master/example-guzzle/test/ExampleGuzzleMeetupAPIClientTest.php) to mirror what you are trying to accomplish.  I appreciate the bug report.   dev-master should have the fix you are looking for.

**Comment by DerManoMann** [comment]
Thanks, I should get some time next week to try this.

**Comment by cfmack** [comment]
I also suggest running this on php 7.1. I ran into an oddity on a
particular pact on Friday when I ran it on php 7.0.

For the Provider side, you need curl and the associated dependencies (some
library needs to be in your path)

**Comment by DerManoMann** [comment]
Yep, using 7.1 anyway  - and I am happy to report that this now works on master!

Thanks heaps for the help and responsiveness.

**Comment by cfmack** [comment]
Sweet. Glad to hear it
