### ISSUE TITLE
Flaky test band aid, retry

### ISSUE THREAD

**Issue by Lewiscowles1986** [pact-foundation/pact-php#287]
Just noticing after some of the good re-work happening, pipelines still flake, so as well as fixing, which might take a minute, I wanted to share some ideas for working around pipeline failures.

https://github.com/marketplace/actions/retry-step is a github action with a fairly nice set of language around retries and even allows you to set a maximum time for jobs (assumed parent process).

shell loops with capturing of errors can also be used.
https://unix.stackexchange.com/questions/82598/how-do-i-write-a-retry-logic-in-script-to-keep-retrying-to-run-it-upto-5-times

**Comment by YOU54F** [comment]
good idea on the retry step, as that is what we do now but manually, will get that in when I am reviewing and going through the FFI stuff next week. ty

**Comment by tienvx** [comment]
I think the pipelines are stable now. We can close this issue for now. We can go back to this idea when it happen again.

**Comment by Lewiscowles1986** [comment]
@tienvx your work is largely why pipelines are so stable. Massive props to you.
