### ISSUE TITLE
Swapping out concrete dependencies for interfaces

### ISSUE THREAD

**Issue by syhol** [pact-foundation/pact-php#3]
Great project, I've been looking for a PHP implementation of pact for about a year now!

However with the existing dependencies it makes it hard for me to pull it into my projects. Would you accept a PR that would:
- Swap out apache/log4php for psr3 - In fact I wonder why you need a logger at all, could you just let exceptions bubble up and let test runners catch it?
- Swap out windwalker/http and php-http/guzzle6-adapter for php-http/httplug - HTTPlug seems to be the foundation for a new HTTP client PSR. 

Thanks

**Comment by mattermack** [comment]
Good stuff, @syhol.   If you can get all the tests to pass, absolutely.  I personally have a Windows dependency, thus running CI on AppVeyor.  https://ci.appveyor.com/project/mattermack/pact-php

I still need to get AppVeyor to run on Pull Requests and handle a specific TreeWalker patch
