### ISSUE TITLE
Migrate to ruby backend

### ISSUE THREAD

**Issue by mattermack** [pact-foundation/pact-php#31]
This ticket is to migrate Pact-PHP to the ruby backend, making it easier to transition to v3.

**Comment by mattermack** [comment]
Random notes
- document for Matching in the new classes
-- PhpPact\Consumer\Matcher\RegexMatcher | Match a value against its data type. | new TypeMatch(12) ?
- build out more robust examples in tests
- confirm provider examples are still accurate

Looking good

**Comment by bethesque** [comment]
Give me a yell if you have any questions.

**Comment by mattermack** [comment]
@bethesque, when working to verify our work, we ran into https://github.com/pact-foundation/pact-ruby-standalone/issues/10

**Comment by mattermack** [comment]
@nbrink91 ,

I worked through some minor documentation and updated examples on [example pact-php-consumer](https://github.com/mattermack/example-pact-php-consumer/tree/mitigrate-to-ruby-backend)

Do you want to do the honors of putting in a pull request for the merge to master?   After that, I'll rename the example project, provide a link to it with better documentation, then we can tag v3!

**Comment by mattermack** [comment]
Merged and closed.
