### ISSUE TITLE
Can't run pact-mock-service when running tests - linux aarch64

### ISSUE THREAD

**Issue by judimator** [pact-foundation/pact-php#314]
Hi everyone!

I want to run consumer test using Pact but got an error

**Env**:

-    Docker image `public.ecr.aws/docker/library/php:8.1.18-fpm-alpine3.17` running on chip Apple M1 Pro (inside container 

-  `$ echo $(uname -sm)` inside container `Linux aarch64`
-   PACT config:
```yml
PACT_MOCK_SERVER_HOST: localhost
PACT_MOCK_SERVER_PORT: 7200
PACT_CONSUMER_NAME: someConsumer
PACT_CONSUMER_VERSION: 1.0.0
PACT_CONSUMER_TAG: master
PACT_PROVIDER_NAME: someProvider
```
**Steps:**

1. run `$ {PROJECT_DIR}/vendor/pact-foundation/pact-php/pact/bin/pact-mock-service`
OR
2. run `$ {PROJECT_DIR}/vendor/pact-foundation/pact-php/pact/lib/ruby/bin/ruby --version`

**Actual result:**
1. `./vendor/pact-foundation/pact-php/pact/bin/pact-mock-service: not found` but the binary file exists
2. `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

**Comment by YOU54F** [comment]
That isn't what I said.

Your Mac M1 != Arm64 Linux.

You can run on a mac m1 with rosetta (which will use the x86_64 binaries)

you can use docker images with the `linux/amd64` to avoid using `linux/arm64` images for unsupported tools

**Comment by YOU54F** [comment]
This is Pact-PHP's current state

| OS     | Ruby      | Architecture   | Supported |
| -------| -------   | ------------   | --------- |
| MacOS  | 2.4.x     | x86_64         | ✅        |
| MacOS  | 2.4.x     | aarch64 (arm64)| 🚧        |
| Linux  | 2.4.x     | x86_64         | ✅        |
| Linux  | 2.4.x     | aarch64 (arm64)| ❌        |
| Windows| 2.4.x     | x86_64         | ✅        |
| Windows| 2.4.x     | x86            | ❌        |
| Windows| 2.4.x     | aarch64 (arm64)| 🚧        |


🚧 are supported under emulation.


see #309 for tracking introducing arm64 linux, and native arm64 macos builds

**Comment by judimator** [comment]
Thank you @YOU54F  I tried to build new image using `linux/amd64` so still result of `sh ./vendor/pact-foundation/pact-php/pact/bin/pact-mock-service` returns `./vendor/pact-foundation/pact-php/pact/bin/pact-mock-service: exec: line 28: /var/www/bmp/vendor/pact-foundation/pact-php/pact/lib/ruby/bin/ruby: not found`. When `pact-foundation/pact-php` runs it the result code is 127.

I vaguely understood what to run  with rosetta?

**Comment by YOU54F** [comment]
See this thread for details on running on alpine

https://github.com/pact-foundation/pact-ruby-standalone/issues/96

If you run it on a debian based image, such as debian stretch you wont need to mess around with installing glibc, which is a dependency of the pact ruby standalone package which pact-php relies on

**Comment by YOU54F** [comment]
See Alpine's source docs for running unsupported software 

https://wiki.alpinelinux.org/wiki/Running_glibc_programs

**Comment by YOU54F** [comment]
Rosetta is only relevant if you are running pact-php directly on your mac, not in a linux container.

Docker runs in emulation mode, if you provide a `--platform linux/amd64` flag, or whichever you want

**Comment by judimator** [comment]
@YOU54F Thanks a mill. I have finally managed to make it happen

**Comment by YOU54F** [comment]
Woop woop!

It would be amazing if you could share your `Dockerfile` if you can, as it _may_ be useful for other pact-php users :)

**Comment by judimator** [comment]
@YOU54F Sure,
```Dockerfile
FROM php:8.1.11-fpm-alpine3.16

RUN apk --update --no-cache add icu-dev libpng-dev $PHPIZE_DEPS \
    && docker-php-ext-install pdo_mysql intl gd opcache \
    && apk del icu-dev libpng-dev \
    && apk --no-cache add icu libpng

ENV GLIBC_VERSION=2.35-r0

RUN apk --no-cache add gcompat bash \
     && wget -O /etc/apk/keys/sgerrand.rsa.pub -q https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
     && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk \
     && apk --no-cache --force-overwrite add glibc-${GLIBC_VERSION}.apk
...
```
