### ISSUE TITLE
Support Pact Specification v4 

### ISSUE THREAD

**Issue by judimator** [pact-foundation/pact-php#318]
Hi there,

I am wondering if PHP library is going to support Pact Specification v4 soon?

If it is no, I guess, changing implementation of PhpPact\Consumer\Model\Interaction will help me to send, say, params for **providerState** (see Example 1):

Example 1:
```json
{
  "providerStates": [
    {
      "name": "an alligator with the given name exists",
      "params": {"name" : "Mary"}
    }, {
      "name": "the user is logged in",
      "params" : { "username" : "Fred"}
    }
  ]
}
```

Thank you!

**Comment by mefellows** [comment]
@tienvx is currently working on a migration to the new Rust FFI, which would support this. We should perhaps pin an issue that is being worked on to raise visibility. What do you think @YOU54F ?

In the meantime, that PR would probably work if you were open to creating one (I know somebody did something similar for Pact JS a few years ago).

**Comment by judimator** [comment]
@mefellows could you tell me what branch(PR) I can use then (there a dozen of them as I see https://github.com/pact-foundation/pact-php/pulls)

**Comment by mefellows** [comment]
I don't know the branch (hence why I `@`ed them). But if you just want parameters, you'll be waiting a while (as the aforementioned work is quite a large amount of change). I'd suggest a PR to the current mainline.

**Comment by judimator** [comment]
@tienvx @YOU54F Any thoughts?

**Comment by YOU54F** [comment]
Hey, 

we will be using the `ffi` branch as per https://github.com/pact-foundation/pact-php/pull/313#issue-1707802513

@tienvx has split out the PR's at the moment, each one is numbered and builds on the last, #280 would be a good place to start

**Comment by mefellows** [comment]
Ah I did see that. I'll pin that one for now for visibility, but I realise that there is not much visibility on this repo that there is a mountain of work going on under the hood. We could also perhaps flesh [this project board](https://github.com/orgs/pact-foundation/projects/7) out.

**Comment by YOU54F** [comment]
Current status is listed in https://github.com/pact-foundation/pact-php/issues/262#issue-1259560884

May be worth closing this down to avoid duplication, but TL;DR is you can test this out today in your projects,  by checking out the instructions in the above pinned issue 👍🏾

**Comment by mefellows** [comment]
I think technically you could make this work with the current version, but it would need somebody to spike/test it (ideally the OP). The ideal solution of course is the proper support for V3/V4 pacts in the referenced issue.

**Comment by YOU54F** [comment]
We've just released an alpha package today with some instructions - HTH

https://github.com/pact-foundation/pact-php/releases/tag/10.0.0-alpha1

**Comment by judimator** [comment]
@YOU54F So I can not use common php FFI but use yours pact_ffi ?

**Comment by judimator** [comment]
I am installing FFI like 

```
RUN apk add --no-cache --virtual .persistent-deps libffi-dev \
    && docker-php-ext-configure ffi --with-ffi \
    && docker-php-ext-install ffi

RUN echo "ffi.enable=true" >> /usr/local/etc/php/conf.d/docker-php-ext-ffi.ini
```

But as I see header file contatns string C++ like string `#include ` which are not supported by FFI(see https://www.php.net/manual/en/ffi.cdef.php#refsect1-ffi.cdef-parameters)

**Comment by YOU54F** [comment]
alpine isn't supported, with the v10.x branch, I am afraid. If you use a debian slim image, things will be smoother

You need the ffi extension, pact-php will take care of loading the library for you.

**Comment by YOU54F** [comment]
just another pointer in code, this is where pact php reads in the header file, and shared lib

https://github.com/pact-foundation/pact-php/blob/ffi/src/PhpPact/Standalone/Installer/Model/Scripts.php

and this is where phps ffi method is called

https://github.com/pact-foundation/pact-php/blob/ffi/src/PhpPact/FFI/Client.php

**Comment by judimator** [comment]
Thanks a lot! @YOU54F

**Comment by YOU54F** [comment]
V4 available in v10.x alpha, and mainlined to `master` branch

See compat table

https://github.com/pact-foundation/pact-php?tab=readme-ov-file#compatibility

fyi alpine support is coming :) https://github.com/pact-foundation/pact-php/pulls
