### ISSUE TITLE
Release 9.x

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-php#319]
The readme states 9.x which was introduced as part of this PR

https://github.com/pact-foundation/pact-php/pull/278

but a release was never put out.

I'm looking to test out #315, #316 and #309 with a view to get them merged and released.

#309 should be a breaking change, as it will drop support for linux 32 bit, so we may want to do both in one hit, when releasing v9, or put out a release now, and then release the latest pact-ruby-standalone under v10.

Just trying to mop up prior to getting on the FFI php train

**Comment by YOU54F** [comment]
![image](https://github.com/pact-foundation/pact-php/assets/19932401/f19e3dd8-17ad-4aaa-993d-aab5d52b8d5e)

**Comment by mefellows** [comment]
Awesome work, thanks for pulling this all together Yousaf!
