### ISSUE TITLE
Release of 10.0.0-alpha1 - inc Pact FFI via Rust-Core

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-php#324]
👋🏾 

It would be good to get a release out of the migration to the pact-reference (rust) core which brings in the new v3/v4 and plugin functionality to pact-php. 

See #262 - This would allow us to provide a tagged release, rather than a branch for testing out the FFI backed implementation.

Composer versioning schemas are here 

https://getcomposer.org/doc/04-schema.md#version

> This must follow the format of X.Y.Z or vX.Y.Z with an optional suffix of -dev, -patch (-p), -alpha (-a), -beta (-b) or -RC. The patch, alpha, beta and RC suffixes can also be followed by a number.

So reading that I propose `10.0.0-alpha1`

In addition, there are some additional packages we may want to bring under the pact-foundation org, or at minimum publish to packagist. They were created by @tienvx.

If we were to transfer over to pact-foundation, we would need to setup access to the packagist webhook, which is currently setup for @mattermack's acc. 

- https://github.com/tienvx/pact-plugin-install
- https://github.com/tienvx/pact-php-csv
- https://github.com/tienvx/pact-php-protobuf

Happy to take any guidance but in lieu of any I will at least publish the pact-php tag from the `ffi` branch as `10.0.0-alpha1` this week

Thanks team!

**Comment by YOU54F** [comment]
cc: @cfmack would you be happy with me putting out a beta release of the ffi work as 10.0.0-alpha1

**Comment by mattermack** [comment]
Thanks. That would be great

**Comment by YOU54F** [comment]
Thank you my friend!

https://github.com/pact-foundation/pact-php/releases/tag/10.0.0-alpha1
