### ISSUE TITLE
Pact-PHP 9.x.x - Support PHPUnit 10

### ISSUE THREAD

**Issue by williamtrevisan** [pact-foundation/pact-php#338]
Hello, there

Is the package update to support PHPUnit v10 in the plans?

**Comment by YOU54F** [comment]
It would be useful I am sure, but we don't have planned work to do so (we don't have a large pool of contributors for pact-php), I just help out on the side to ensure contributors PR's are being merged.

Can you provide details, along with source references for the update to PHPUnit v10

- any new features
- any breaking changes

We would welcome anyone to fork the repository and have a look at updating to support!

**Comment by antonkomarev** [comment]
@YOU54F PHPUnit 10 removed Listeners concept.

```
1) Test results may not be as expected because the XML configuration file did not pass validation:

  Line 18:
  - Element 'listeners': This element is not expected.
```

Now it uses new Events concept. You can read about this changes in [official announcement](https://phpunit.de/announcements/phpunit-10.html) and how to work with new concept in one of [community guides](https://localheinz.com/articles/2023/02/14/extending-phpunit-with-its-new-event-system/).

**Comment by YOU54F** [comment]
> @YOU54F PHPUnit 10 removed Listeners concept.
> 
> ```
> 1) Test results may not be as expected because the XML configuration file did not pass validation:
> 
>   Line 18:
>   - Element 'listeners': This element is not expected.
> ```
> 
> Now it uses new Events concept. You can read about this changes in [official announcement](https://phpunit.de/announcements/phpunit-10.html) and how to work with new concept in one of [community guides](https://localheinz.com/articles/2023/02/14/extending-phpunit-with-its-new-event-system/).

Thanks for the additional context @antonkomarev, hopefully this will be helpful is anyone wants to help out.

I don't believe anyone from the Pact team is likely to pick up this request themselves , due to work mainly taking place on the Pact rust core and rewritten v10.x version now mainlined to master

**Comment by YOU54F** [comment]
10.x beta supports phpunit 10.

We will accept PR's to backport but as we are unlikely to pick this up, I am going to close this issue off.

Thanks for raising
