### ISSUE TITLE
[Feature Enhancement] - v10.x - Support logging to file

### ISSUE THREAD

**Issue by judimator** [pact-foundation/pact-php#341]
Hi there,

During my work I found the following issue

**Env:**
- pact-php: 10.0.0-alpha2
- phpunit: 10.3.4

**Step to reproduce:**

- Set PACT_LOG var (for example ./log/pact.log)
- Run a test

**Expected result:**
The file exists

**Actual result:**
The file not found

**Comment by tienvx** [comment]
Hi @judimator , thanks for reporting the issue.

After a quick look at pact-reference and pact-php (version 10 alpha) projects, I think:
* Currently only `PACT_LOGLEVEL` is supported
* `PACT_LOG` is the code leftover from version 9, and it does not do anything, and should be removed
* [This code](https://github.com/pact-foundation/pact-reference/blob/master/php/src/consumer-plugin.php#L13) can provide similar behavior, but I didn't implement it yet. I think we can find a way to use it in the future alpha version

cc @YOU54F Thanks for the useful code . Do you know how pact's implementation in other languages handle this one?

**Comment by YOU54F** [comment]
Hey,

Pact-JS doesn't support logging to file at the moment ( I made a draft PR here https://github.com/pact-foundation/pact-js-core/pull/428)

The current interface between the ffi for init'ing with the logger is here

https://github.com/pact-foundation/pact-js-core/blob/master/native/ffi.cc#L12

There are some convenience functions to setup a logger

https://docs.rs/pact_ffi/latest/pact_ffi/log/index.html


- [pactffi_log_to_buffer](https://docs.rs/pact_ffi/latest/pact_ffi/log/fn.pactffi_log_to_buffer.html)	Convenience function to direct all logging to a task local memory buffer.
- [pactffi_log_to_file](https://docs.rs/pact_ffi/latest/pact_ffi/log/fn.pactffi_log_to_file.html)⚠	Convenience function to direct all logging to a file.
- [pactffi_log_to_stderr](https://docs.rs/pact_ffi/latest/pact_ffi/log/fn.pactffi_log_to_stderr.html)	Convenience function to direct all logging to stderr.
- [pactffi_log_to_stdout](https://docs.rs/pact_ffi/latest/pact_ffi/log/fn.pactffi_log_to_stdout.html)	Convenience function to direct all logging to stdout.

I believe these call logger_apply, where as calling `pactffi_logger_attach_sink` allows you to setup multiple loggers, prior to calling `pactffi_logger_apply`

I did notice that once you've called `pactffi_logger_apply` you can't change the logger settings within the same process, so you change the log level or mode for a particular test (it caused me issues when trying to test pact-python with the ffi, where there were unit tests that tested log levels)


Further examples

- [Logging Example in Pact Ref](https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/examples/logging/src/main.c)
- [GoLang](https://github.com/pact-foundation/pact-go/blob/master/internal/native/mock_server.go#L240)

**Comment by YOU54F** [comment]
in my pr for pact python i tried this out to set the log level at init time, depending on the env vars presented by the user

https://github.com/pact-foundation/pact-python/pull/367/files#diff-c666652e61742bd29834872c24326ac8e8ff8be3ed3d645fe596968ed9013938R66

instructions 

https://github.com/pact-foundation/pact-python/pull/367/files#diff-b059f16e86de3ca400fc1d0b7a623bb0aa703cd3357d45dc0cc931b7f3f0a3e3R148

so it can easily be controlled externally to dump to a file, buffer etc or set a log level. that code shown only sets up one logger sink though, so if your code relies on pulling anything back from a log buffer and it’s instead been setup with a file or stdout, the data won’t be present.

**Comment by tienvx** [comment]
Implemented in #689, will be available in v10.1
* The variable `PACT_LOG` is added back from v9
* Need to define PHPUnit extension `PactLoggingExtension`
