### ISSUE TITLE
Move PHPUnit to dev requirements

### ISSUE THREAD

**Issue by Vinimaks** [pact-foundation/pact-php#345]
Hi there,

Currency I'm using version 8.1, where phpunit/phpunit is >=8.5.23 but I cannot update to version 9 because the version is limited < 10. Is it possible to move phpunit/phpunit to require-dev section so it can be used in projects with phpunit >= 10?

**Comment by tienvx** [comment]
Hi @Vinimaks 

I'm a contributor of version 10. From version 10 alpha, `phpunit` has been moved to `require-dev` section.

I  didn't contribute to version <= 9 much so I can't tell, but from what I checked in the code, phpunit is required (https://github.com/pact-foundation/pact-php/blob/master/src/PhpPact/Consumer/Listener/PactTestListener.php), not require-dev

**Comment by YOU54F** [comment]
Thanks @tienvx for confirming.

@Vinimaks looks like the resolution is to move to the v10.x version, or look to backport in the release/9.x.x and update to support phpunit >= 10

That can be tracked in https://github.com/pact-foundation/pact-php/issues/338 so going to close this down
