### ISSUE TITLE
FFI > Free unmanaged memory when no longer used

### ISSUE THREAD

**Issue by tienvx** [pact-foundation/pact-php#371]
There are 2 places that create unmanaged memory:

- https://github.com/pact-foundation/pact-php/blob/ffi/src/PhpPact/FFI/Model/ArrayData.php#L44
- https://github.com/pact-foundation/pact-php/blob/ffi/src/PhpPact/FFI/Model/BinaryData.php#L34

There is a potential memory leak if it's not handled.

- I already call `FFI::free` for the first one (https://github.com/pact-foundation/pact-php/blob/ffi/src/PhpPact/FFI/Model/ArrayData.php#L58), but I'm not sure it's correctly handled.
- I don't know solution for the second one

**Comment by tienvx** [comment]
* `FFI::free` work fine in `ArrayData`
* I changed from `unmanaged` data to `managed` data in `BinaryData`

**Comment by YOU54F** [comment]
Is this resolved now @tienvx

**Comment by tienvx** [comment]
I think it's resolved
