### ISSUE TITLE
Feedback Thread:- Pact PHP v10 alpha FFI

### ISSUE THREAD

**Issue by slt** [pact-foundation/pact-php#377]
Not an issue as such, just want to say I love it. (I'm using 10-alpha3)

It's so much faster and simpler, and I'm looking forward to using some of the newer Pact specification features.

My API tests came across easily without much fuss.

I had to convert my message provider tests from the callbacks to the new format which was a little time-consuming but it makes so much more sense now, rather than having a provider verifier in PHP as a PHPunit test, I'm able to just use the API endpoint and the standalone provider verifier, which makes it more consistent with the non-message verifiers.

My only feedback is maybe the documentation should be updated to spell out the standalone provider verifier should be used along with the API endpoint (and an example), the moment it only talks about the API endpoint and I had to guess the rest, which migrating from the previous version was rather different.

https://github.com/pact-foundation/pact-php/tree/ffi#provider-side-message-validation

Looking forward to the proper v10 release.

**Comment by tienvx** [comment]
Hi @slt 

I am not using previous versions so feedback like this is valuable to me.

> ... I'm able to just use the API endpoint and the standalone provider verifier

> My only feedback is maybe the documentation should be updated to spell out the standalone provider verifier should be used along with the API endpoint

I'm curious about the "standalone provider verifier" you are using. Currently I'm aware of 3 ways to verify provider:

1. Ruby's Pact Verifier
  1. https://github.com/pact-foundation/pact-provider-verifier
  2. Available as CLI and docker image
  3. I assume it only support pacts with specification version <= 2. I could be wrong though. Maybe all pact verifier tools are specification-independent
2. Rust's Pact Verifier
  1. https://github.com/pact-foundation/pact-reference/releases/tag/pact_verifier_cli-v1.0.1
  2. Available as CLI
  3. It support pacts with any specification version (currently 4)
3. PHP's Pact Verifier
  1. https://github.com/pact-foundation/pact-php/tree/ffi#provider-verification
  2. Available as a PHPUnit test
  3. It support pacts with any specification version (currently 4)

I'm only familiar with `#3`, and use it in all examples in https://github.com/pact-foundation/pact-php/tree/ffi/example, plus my own private project (just like another test case).

If I understand your comment correctly, I assume you are using `#1`.  And I also assume you are still using specification version 2. If so, can you share your experience about this?

> it makes so much more sense now, rather than having a provider verifier in PHP as a PHPunit test

For me, one downside of using `#3` is: the PHPUnit test is duplicated again and again in all providers.

**Comment by slt** [comment]
Thank you @tienvx for all your hard work.

When we initially adopted Pact a year ago we used the Ruby standalone provider, before moving to the Rust standalone in march.
We use the pactfoundation/pact-ref-verifier docker image.

To verify the contracts from our PHP service with it, we just set the base_url env var to the pact-messages endpoint we built, it was straight forward.

We have a lot of different projects/microservices in different languages and testing frameworks so the standalone verifier has always appealed to us, & with the provider state endpoints, we can set up any test data we need.

Our existing contracts from Pact PHP v8 were pactSpecification 2.0.0
The ones generated from the 10-alpha3 are now pactSpecification 3.0.0, 

Moving to pactSpecification 3.0.0 didn't require any changes for the contracts themselves, the only change I had to do was update our config instances (MockServerConfig, PactMessageConfig).

**Comment by YOU54F** [comment]
we are very pleased to announce that pact-php v10 is now out of beta.

https://github.com/pact-foundation/pact-php/releases/tag/10.0.0

thanks @tienvx for your heroic effort and everyone who helped contributed along the way

**Comment by mefellows** [comment]
Massive news and congratulations Tien 👏 . Wonderful to see PHP hit this milestone and clearly it's hitting the mark :)

P.S> @slt if you're ever down in Melbourne, give the Pact(Flow) team a shout (a bunch of the Pact maintainers are in Melbourne)
