### ISSUE TITLE
Duplicate Host header on Provider side

### ISSUE THREAD

**Issue by aeacusvol** [pact-foundation/pact-php#41]
I have a contract below, and when attempting to verify this contract on the provider side I'm having an issue where the Host header is getting set twice causing the client to get a 404.

I have tracked the issues down to the WindWalker Request calling `withUri()` on line 34 of `HttpRequestMessageMapper` which applies a Host header to the request, and then the foreach on line 38 applying the Host header again from the request.

As far as I can tell this could be fixed by removing the Host from the contract which seems like a poor choice, or adding something like so to `HttpRequestMessageMapper`
```
foreach ($request->getHeaders() as $header_key => $header_value) {
    if (! $httpRequest->getHeader($header_key)) {
        $httpRequest = $httpRequest->withAddedHeader($header_key, $header_value);
    }
}
```

My pact verifier code is
```$pactVerifier = new \PhpPact\PactVerifier('http://user-api');
$pactVerifier->providerState("GET to user details")
    ->serviceProvider('userapi', new \Windwalker\Http\HttpClient())
    ->honoursPactWith('newsapi')
    ->pactUri('/pacts/newsapi-userapi.json')
    ->verify();
```

Contract
```{
    "provider": {
        "name": "UserApi"
    },
    "consumer": {
        "name": "NewsApi"
    },
    "metadata": {
        "pactSpecificationVersion": "2.0.0"
    },
    "interactions": [
        {
            "description": "A GET request with a base /v1/user",
            "providerState": "GET to user details",
            "request": {
                "method": "GET",
                "path": "/v1/user",
                "headers": {
                    "Host": "user-api",
                    "X-Access-Email": "ZW1haWxAdGhlZHJ1bS5jb20=",
                    "X-Access-Token": "dG9rZW4="
                }
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": {
                    "user": {
                        "id": "59e4d767-5539-4bf6-b44c-6651c7a69001",
                        "email": "email@gmail.com",
                        "firstName": "Wilhelmine",
                        "lastName": "Doyle",
                        "access": "token"
                    }
                }
            }
        }
    ]
}
```

**Comment by mattermack** [comment]
@aeacusvol that seems like a simple change.  Want to put in a pull request and we can see if it passes our tests?   

What version are you using?  I assume 2.1.

One thing to keep in mind, @nbrink91 and I are working to move to the ruby backend.  This has some changed behavior that does not match 1x1 to the Pact-PHP but inline with other implementations (good thing).   We're working on that on a feature branch, which will result in Pact-PHP v3.0.0 (not Pact specification v3 support yet).  

I can try to geek out on this soon.

**Comment by mattermack** [comment]
Yes, it actually looks like that is a special key word for Windwalker (I admittedly did not dig too deep on the insides of the library).   I added some extra logic to handle duplicates like you mentioned, but I do not think that solves your host issue

**Comment by mattermack** [comment]
You can pull from dev-master if you need this.  There is a minor update I hope to get to in Pact-PHP 2.X before we cut to Pact-PHP 3.X soon.   If I do not get to it, I'll tag master with 2.X before the merge.

**Comment by mattermack** [comment]
@aeacusvol I merged this issue in along with Add mock http client to 2.X #42

I tagged the version as 2.2.0.   It should simplify the consumer side a little bit more
