### ISSUE TITLE
Provider verifier verifies multiple consumers if PACT file is given

### ISSUE THREAD

**Issue by judimator** [pact-foundation/pact-php#447]
**Initial state**
- **pact-php:^9.0**
- One provider, called **Provider 1**
- Multiple consumers for Provider 1, call them **Consumer1**, **Consumer2**
- Pacts of **Consumer1**, **Consumer2** are published. Contract for **Consumer2** is not valid for  **Provider 1**

**Step to reproduce**
- Run the following script
```php
$config = new VerifierConfig();
$config
    ->setProviderName('Provider1')
    ->setProviderVersion(getenv('PACT_PROVIDER_VERSION'))
    ->setProviderBranch(getenv('PACT_PROVIDER_BRANCH'))
    ->setProviderBaseUrl(new Uri('http://localhost:7202'))
    ->setBrokerUri(new Uri(getenv('PACT_BROKER_URL')))
    ->setBrokerUsername(getenv('PACT_BROKER_HTTP_AUTH_USER'))
    ->setBrokerPassword(getenv('PACT_BROKER_HTTP_AUTH_PASS'))
    ->setPublishResults(true)
    ->setVerbose(true)
    ->setProviderStatesSetupUrl('http://127.0.0.1:7202/states/');

$verifier = new Verifier($config);
$verifier->verify('Consumer1', null, getenv('PACT_CONSUMER_VERSION'));
```

**Expected result**
- Only contract for **Consumer1** verified

**Actual result**
- Contract result for **Consumer2** presented in verification output

**Comment by mefellows** [comment]
Looking at the following line, I can't quite see how that could find other consumers - unless there is a bug in the broker (doubtful):
> https://github.com/pact-foundation/pact-php/blob/60979406a5877e1eb71860afcb96dd783a8b15b6/src/PhpPact/Standalone/ProviderVerifier/Verifier.php#L146

Can you please share some logs with verbose/debug logging enabled to help us understand what calls are being made to the broker?

**Comment by mefellows** [comment]
Ah, I suspect that because the Verifier has been given a broker URL, it is also dynamically fetching pacts. The logs and terminal will show this, however.

**Comment by judimator** [comment]
@mefellows Yeah, I think that is the cause, so if broker data given it tries to verify not only given file but all pacts as well
