### ISSUE TITLE
Question on  \Countable check

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#46]
Hi there,

I've got a question around https://github.com/pact-foundation/pact-php/commit/33e40197105444e7a05d86bb13caf5b37166b190#diff-6bc3b218ac6fc84141fc0d66d1de9160

The `instanceof \Countable` check does mean it is no longer possible to use plain arrays and it seems I can't get any into the pact files?

**Comment by cfmack** [comment]
I thought I replaced all of these. There's no reason it can't be an array,
stdClass, or Countable

**Comment by DerManoMann** [comment]
Ah, maybe I didn't make myself clear - I am using PHP 7.1 and using a plain array `[]` does not pass the test, so matching rules are ignored.

This does not print the array for me:
````
$arr = [1];
if ($arr instanceof \Countable) {
  print_r($arr);
}
````

**Comment by DerManoMann** [comment]
It also makes publishing json files that include matching rules drop those along the way...

**Comment by mattermack** [comment]
That was a bug.   I just checked in an alternative to master.  Can you test master then I can add a new tag?

**Comment by DerManoMann** [comment]
Will do tomorrow - thanks

**Comment by DerManoMann** [comment]
Actually, had some unexpected downtime - tested with 5b3b7078f3 and that is looking good!
