### ISSUE TITLE
matching 10 with 10.0

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#47]
Hi there,

I've hit another edge case with some PHP flavour on top. I am trying to create a pact with an API that will return doubles like `10.0`. However, it doesn't seen to be possible to enforce the decimal 0 in PHP - instead the value is always encoded as `10`

My understanding is that the only supported matchers are type and regex, with regex only apllying to string values. That doesn't leave a lot of options, unless I am missing something?

**Comment by bethesque** [comment]
Try specifying `10.1`. Pact JS has the same problem - it casts anything with a zero decimal to an integer instead of a double. The `. 1` ensures it stays a double.

**Comment by DerManoMann** [comment]
That is easy for you to say - they API I work against returns 10.0, so always at least one decimal point. I suppose to make it clear that the value is a double...

To be clear, this only affects the pact files, not the actual functionallity - only way so far seems to patch the pact file before publishing.

However, even that is hard because the broker connector deserialized/validates/serialized it again, so short of overriding the `PactBrokerConnector`'s `publish()` method I have not found anything to get this working.

**Comment by DerManoMann** [comment]
So, right now I can see two approaches to get this working:
1. add custom callback to replace the default `\json_encode($body);` in the broker connector
2. have a matcher that allows to comare the effective value or that can deal with different representations of the same (numeric) value

Obviously, option 2 seems nicer...

**Comment by DerManoMann** [comment]
Had another think about your suggestion - if I understand that correct you mean that by specifying 10.1 I force the double and then I match on type only?
Hmm, that should work, I guess...

**Comment by bethesque** [comment]
Yes, exactly. Generally speaking, you pretty much always want to match based on types when you're doing the provider verification, otherwise your tests become quite brittle. Have a read of this section on matching best practice: https://github.com/pact-foundation/pact.io/blob/test/documentation/matching.md#best-practice

**Comment by bethesque** [comment]
Also, I can't reproduce this problem of the double turning back into an integer. Can you double check for me?

```ruby
~ $ irb
irb(main):001:0> require 'json'
=> true
irb(main):002:0> {test: 1.0}.to_json
=> "{\"test\":1.0}"
irb(main):003:0> JSON.parse({test: 1.0}.to_json)
=> {"test"=>1.0}
```

**Comment by DerManoMann** [comment]
Great, thanks for your help.

As for the turning back into integer - yesterday I didn't have time to actually run the verification, all I did was push JSON with a 10.0 into the broker and then look at it using the HAL browser.
This morning I did run the tests and they pass!
So it looks like the broker is doing the right thing and it is just the HAL browser that loses the format...
Either way, I've changed the test as per your recommendation to expect a (random) double with a decimal digit and then match on type.

**Comment by bethesque** [comment]
Can I suggest you use a hardcoded number, not a random one? If you use a random one, the pact will be considered to have changed each time, and you won't be able to use the "pre-verification" feature of the broker (which works out if the pact has changed and if it hasn't, it applies the previous verification results to the new pact publication)

**Comment by DerManoMann** [comment]
Ha! Bad choice of words. Yes, I picked a static number, but unrelated to any testing/expectations other than the type (double).

**Comment by bethesque** [comment]
Perfect!
