### ISSUE TITLE
'given' and 'uponReceiving' should be swapped in InteractionBuilderInterface

### ISSUE THREAD

**Issue by samuelnogueira** [pact-foundation/pact-php#54]
According to documentation, provider state should be set in the `given` clause of the interation: https://docs.pact.io/documentation/provider_states.html
The methods `given` and `uponReceiving` in `\PhpPact\Consumer\InteractionBuilderInterface` seem to be swapped in this library, as provider state is being set by `uponReceiving` and request description is being set by `given`.
The issue in readability becomes clear when comparing the Ruby example with the PHP one:
**Ruby**
```ruby
describe MyServiceProviderClient do

  subject { MyServiceProviderClient.new }

  describe "get_something" do
    context "when a thing exists" do
      before do
        my_service.given('a thing exists').
          upon_receiving('a request for a thing').
          with(method: 'GET', path: '/thing').
          will_respond_with(
            status: 200,
            headers: { 'Content-Type' => 'application/json' },
            body: { name: 'A small something'})
      end
    end
  end
end
```

**PHP**
```php
(new InteractionBuilder($mockServerConfig))
    ->given('a request for a thing')
    ->uponReceiving('a thing exists')
    ->with(
        // (...)
    )
    ->willRespondWith(
        // (...)
    );

**Comment by nbrink91** [comment]
@samuelnogueira, thanks for catching this. It has been fixed and the documentations been modified to hopefully make the example more clear.
