### ISSUE TITLE
Client error: `POST http://host.docker.internal:8080/interactions` resulted in a `404 Not Found

### ISSUE THREAD

**Issue by aformuli** [pact-foundation/pact-php#560]
Hi,
I am using symfony framework with Docker. I have added a contract test with below code but I get No route found for POST http://host.docker.internal:8080/interactions; (404 Not Found).

        $request = new ConsumerRequest();
        $request->setMethod('GET')
            ->setPath('/api/user/<id>')
            ->addHeader('Accept', 'application/json')
            ->addHeader('Content-Type', 'application/json');

        $response = new ProviderResponse();
        $response->setStatus(200)
            ->addHeader('Content-Type', 'application/json')
            ->setBody([
                "id" => "<id>",
                "contact_id" => "<id>"
            ]);

        $config  = new MockServerConfig();
        $config->setHost('host.docker.internal');
        $config->setPort(8080);

        $builder = new InteractionBuilder($config);
        $builder->given('a user exists')
            ->uponReceiving('Get user for id /api/user/{id}')
            ->with($request)
            ->willRespondWith($response); -> **It fails here**

        $client = new Client(['base_uri' => $config->getBaseUri()]);

        $controller = new UserController($client, $config->getBaseUri()->getHost());
        $response = $controller->fetch(new Request([], [], ['id' => '<id>']));
        $builder->verify();
        $this->assertSame(200, $response->getStatusCode());

I don't get where the /interactions route is set or if I am missing config for this path.

Thanks

**Comment by mefellows** [comment]
You may need to explain your setup here, it's not clear why docker is involved and how it is configured to work with Pact. 

Specifically, what is this doing:
```
    $config  = new MockServerConfig();
    $config->setHost('host.docker.internal');
    $config->setPort(8080);
```

I'm _guessing_ maybe this is where your provider API is running? If so, that's not how Pact is intended to work. The mock server is that - a mock - and is setup by Pact automatically based on the `$builder` definition. This could explain the `404` - your API is not the Pact mock server and doesn't know how to respond to the administration calls.

**Comment by aformuli** [comment]
Thanks Matt,

That is what I was confused of. I changed the the mock server config and it works now.

**Comment by mefellows** [comment]
Great, no worries :)
