### ISSUE TITLE
What's the purpose of running `VerifyInteractions`

### ISSUE THREAD

**Issue by ruudk** [pact-foundation/pact-php#6]
I don't fully understand why my consumer test should call `VerifyInteractions`. 

If my consumer requests endpoints that are not mocked, an error will be already be thrown:
```
RuntimeException: No mock responses for were found for this request:
A GET request with URL: localhost
	has path: /v1/convert/GBP/USD
	has port:
	has query:
	has headers:
		User-Agent with value GuzzleHttp/6.2.1 curl/7.52.1 PHP/7.2.0RC1
		Host with value localhost
```

If I add mocked endpoints that are not called, they are not catched by `VerifyInteractions`

**Comment by mattermack** [comment]
Yes, I've been thinking about that.   Perhaps it is useful to call right before the Build step.   Overall, that's admittedly a bug.

**Comment by bethesque** [comment]
Verify must be called after each test, preferably by the framework, but by the user if that's not possible. See this example: 
https://github.com/pact-foundation/pact-mock_service/blob/master/script/example.sh

**Comment by cfmack** [comment]
Thanks, @bethesque

**Comment by mattermack** [comment]
Thanks @bethesque

**Comment by bethesque** [comment]
I see that Neil has given you a good explanation in the issue you raised in the .net repo.

**Comment by bbat** [comment]
Yes. Thank you Beth. Have a good day.

Le ven. 25 mai 2018 à 01:18, Beth Skurrie <notifications@github.com> a
écrit :
