### ISSUE TITLE
With symfony/process v4, ProcessBuilder is not found.

### ISSUE THREAD

**Issue by KonstantinCodes** [pact-foundation/pact-php#60]
The vendor package `symfony/process` v4 doesn't contain the ProcessBuilder any more.
See the following [cleanup commit](https://github.com/symfony/process/commit/8bdb5476df7d0f1f5243ff1a773173d81c23f23c#diff-3bc59476cba74826b9a882145d01f44a).

The use of ProcessBuilder has been deprecated since version 3.3

This creates following error during test runs on a symfony 4 installation on the Provider side:
1) App\Tests\PactTest::testPactVerifyConsumer
Error: Class 'Symfony\Component\Process\ProcessBuilder' not found

I proposed a fix in #61

**Comment by mattermack** [comment]
Thanks, @KonstantinCodes
