### ISSUE TITLE
Please update to the latest pact standalone version 

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-php#64]
This is to fix https://github.com/pact-foundation/pact-mock_service/issues/87#issuecomment-385540345

Get the latest version here https://github.com/pact-foundation/pact-ruby-standalone/releases

**Comment by nbrink91** [comment]
@bethesque, the update was made a few weeks ago. The pact standalone files were not being deleted when PACT was updated. @siad007 just made a PR to now delete the files when updating via composer.

**Comment by bethesque** [comment]
👍
