### ISSUE TITLE
Nested array as passed params in given state

### ISSUE THREAD

**Issue by judimator** [pact-foundation/pact-php#690]
Hi there,

I am wondering is there a chance to pass nested array as params. Currently it supports only `array<string, string>` params. 

### Code to reproduce

```php
$config = new MockServerEnvConfig();
$builder = new InteractionBuilder($config);
$builder
    ->given('User exist', [
        'date' => [
            'id' => 1,
            ...
        ],
        'meta' => [],
    ])
    ...
```

### Version
pact-php:10.0.0

**Comment by tienvx** [comment]
Thank @judimator for reporting the issue. This feature will be available in 10.1

**Comment by judimator** [comment]
@tienvx Thanks! Would you tell me when you gonna perform that release?

**Comment by tienvx** [comment]
I can't say for sure, but it may happen within 2 weeks. Would you like an alpha version to try it out?

**Comment by judimator** [comment]
@tienvx  Yeah, why not, but I didn't find alpha among all releases...

**Comment by tienvx** [comment]
I released a new version. You can try it out using the tag `10.1.0-beta1`
