### ISSUE TITLE
Use arrays instead of stdClass

### ISSUE THREAD

**Issue by ruudk** [pact-foundation/pact-php#7]
Any special reasons to use stdClass while doing json_decode? 

I found that there are typing issues because sometimes something is an array and sometimes its a stdClass. 

Can I create a PR to remove all stdClass usages and just use plain arrays instead?

**Comment by mattermack** [comment]
@ruudk ,
We're definitely taking pull requests.  I just wrapped up a full testing on spec 1.1.   With the Pact foundatoin, I have AppVeyor setup to run the tests on Windows: https://ci.appveyor.com/project/mattermack/pact-php

Assuming the tests pass, pull requests are definitely welcome.  I appreciate you putting in these issues.  I'll have to work through them with the 1.1.0 version to see if they are still open.  If you could look at them again, let me know.
