### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PhpPact\Consumer\Exception\MissingEnvVariableException

### ISSUE THREAD

**Issue by arkonchik** [pact-foundation/pact-php#74]
In version 3.0.3
When no env var setup and creating class  MockServerEnvConfig.
I've got 
Fatal error: Uncaught Error: Class 'PhpPact\Consumer\Exception\MissingEnvVariableException' not found in 
vendor/mattersight/phppact/src/PhpPact/Standalone/MockService/MockServerEnvConfig.php on line 44

It's seems that MissingEnvVariableException class has wrong namespace

vendor/mattersight/phppact/src/PhpPact/Standalone/Exception/MissingEnvVariableException.php

**Comment by mattermack** [comment]
Briefly looking at the code, things appear correct.  I'll have to dig a little deeper to find out.   PHPStorm shows no autohinting error either

**Comment by mattermack** [comment]
I just tagged 3.1.0

**Comment by arkonchik** [comment]
thanks
