### ISSUE TITLE
Cannot compare "empty" body response

### ISSUE THREAD

**Issue by arkonchik** [pact-foundation/pact-php#75]
If I set to pact brocker response body like this "{}"
When I compare results at provider side I have an error
` returns a response which has a matching body
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example

       Actual: {}

       Diff
       --------------------------------------
       Key: - is expected 
            + is actual 
       Matching keys and values are not shown

       -{}
       +{
       +}
`
How can I assert that response will be empty?

**Comment by bethesque** [comment]
What are your expected and actual content types?

**Comment by bethesque** [comment]
Also, no, you can't assert that you get an empty JSON response body. An empty JSON body expectation for the response basically says "give me any hash". The reason for this is that we follow postel's law for response matching, which means that any unexpected keys in the response are ignored. If you follow that rule to the extreme, it means that anything more than `{}` will be ignored, hence `{}` matches everything. It's a bit of a gotcha.

**Comment by arkonchik** [comment]
It make sense.
I'm confused that expected response body correctly set to pact broker, but when it comparing by verifier tool, it try to do this, but can't "correctly" do.

**Comment by bethesque** [comment]
Hm. That looks like it should work. Can you try and recreate the issue with a fork of https://github.com/pact-foundation/pact-ruby-standalone-e2e-example please?

**Comment by arkonchik** [comment]
Yes, I will try it in few days.

**Comment by arkonchik** [comment]
Sorry it was my mistake.
I did not correctly set up response body to broker.
For now if i set up to broker empty body it did not set it all, is this expected behavior?
Debug looks like this

```
D, [2018-06-01T06:22:35.697324 #483] DEBUG -- : {
  "status": 201,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": {
  }
}

```

And in broker ui like this:
```
{
  "status": 201,
  "headers": {
    "Content-Type": "application/json"
  }
}
```

**Comment by bethesque** [comment]
Again, can I ask you to replicate the problem using the e2e-example?

**Comment by arkonchik** [comment]
https://github.com/arkonchik/pact-ruby-standalone-e2e-example/tree/interactions-with-empty-request-here is an example.
It will correctly setup in example.
And later i did request from hal-browser to see pact data in json and understood that ui can simply hide empty "body" response, thanks.
