### ISSUE TITLE
PhpPact\Standalone\ProviderVerifier\Verifier verification issue

### ISSUE THREAD

**Issue by arkonchik** [pact-foundation/pact-php#76]
In 3.1 version I can verify provider pact in next ways:

1. Verification problem
- verify latest tag for provider-consumer
```
public function verify(string $consumerName, string $tag = null): self
    {
        // Add tag if set.
        if ($tag !== null) {
            $uri = $this->config->getBrokerUri()
                ->withPath("pacts/provider/{$this->config->getProviderName()}/consumer/{$consumerName}/latest/{$tag}");
        } else {
            $uri = $this->config->getBrokerUri()
                ->withPath("pacts/provider/{$this->config->getProviderName()}/consumer/{$consumerName}/latest");
        }
```
 
- verify all consumers for provider 
```
`public function verifyAll()
    {
        $arguments = $this->getBrokerHttpClient()->getAllConsumerUrls($this->config->getProviderName(), $this->config->getProviderVersion());

```
- verify all consumers for tag
```
public function verifyAllForTag(string $tag)
    {
        $arguments = $this->getBrokerHttpClient()->getAllConsumerUrlsForTag($this->config->getProviderName(), $tag);
```

But how can I verify pact for certain consumer version?
This doc https://github.com/pact-foundation/pact_broker/wiki/Pacticipant-version-numbers told that consumer version number can be git sha, but for now I can't verify that provider supports pact for consumer with certain version, through this PhpPact\Standalone\ProviderVerifier\Verifier - class 
Maybe need another one method like?
`public function verifyVersion(string $consumerName, string $version = null): `

2. Property set up problem
Can we move this from const to var and set up from constructor at Verifier?
```
const PROCESS_TIMEOUT      = 60;
const PROCESS_IDLE_TIMEOUT = 10;
```

**Comment by arkonchik** [comment]
Maybe it will better if I do pull request?

**Comment by mattermack** [comment]
Playing with Pact Broker, I think one cannot use both a tag and a consumer version.   Is that right @bethesque ?  

Assuming that is true, a simple code change is sufficient. 

```
public function verify(string $consumerName, string $tag = null, string $consumerVersion = null): self
{
        $path = "pacts/provider/{$this->config->getProviderName()}}/consumer/{$consumerName}/";
        if ($tag) {
            $path .= "latest/{$tag}/";
        }
        else if ($consumerVersion) {
            $path .= "version/{$consumerVersion}/";
        } else {
            $path .= "latest/";
        }

        $uri = $this->config->getBrokerUri()->withPath($path);

        $arguments = \array_merge([$uri->__toString()], $this->getArguments());

        $this->verifyAction($arguments);

        return $this;
}
```

**Comment by mattermack** [comment]
I merged this into dev-master.   Because #79 requires an upgrade to PHP (7.1) and a major upgraded of PHPUnit 7.X, PactPHP will become 4.0.0.  

@arkonchik, I'd love your feedback on both this issue and the breaking change in PHPUnit 7.X

**Comment by bethesque** [comment]
You can either use a consumer version number `/pacts/provider/{provider}/consumer/{consumer}/version/{consumer-version-number}` OR the latest tag `/pacts/provider/{provider}/consumer/{consumer}/latest/{tag}` to retrieve a pact. Does that answer your question @mattermack ?

**Comment by mattermack** [comment]
That is exactly what I thought!   I was concerned that I did missed some use cases and wanted to ask the group.
