### ISSUE TITLE
PHPUnit 7.1.3 PactTestListener::addError declaration incompatible issue

### ISSUE THREAD

**Issue by macoto-liu** [pact-foundation/pact-php#79]
```
# vendor/bin/phpunit -version
PHPUnit 7.1.3 by Sebastian Bergmann and contributors.
```

I'm using phpunit 7.1.3, when setup the default PHPUnit listener in phpunit.xml. phpunit running failed because of addError declaration. 

```
# composer test -- --debug
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> vendor/bin/phpunit '--debug'

Fatal error: Declaration of PhpPact\Consumer\Listener\PactTestListener::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in /var/www/html/vendor/mattersight/phppact/src/PhpPact/Consumer/Listener/PactTestListener.php on line 23
```

**Comment by macoto-liu** [comment]
I"m using `"mattersight/phppact" : "3.1.1"`

**Comment by mattermack** [comment]
I validated this.   It appears we run on PHPUnit 6.X but not 7.X without changes.

**Comment by mattermack** [comment]
Funny enough, the PHPUnit 7.1 documetation says to use \Exception, rather than \Throwable
https://phpunit.readthedocs.io/en/7.1/extending-phpunit.html?highlight=addError

But the code (https://github.com/sebastianbergmann/phpunit/blob/d96549ddd7925645d069de0bdd786fb365c0c372/src/Framework/TestListener.php#L20) says Throwable.

**Comment by mattermack** [comment]
I merged this into dev-master.   Because this requires an upgrade to PHP (7.1) and a major upgraded of PHPUnit 7.X, PactPHP will become 4.0.0.  I'd love your feedback.
