### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by gradzio** [pact-foundation/pact-php#82]
Hey,

It is quite difficult to integrate package with newest (5.6) version of Laravel. It is because you require specific version of symfony console (used in both projects). I understand that you need it for example but i dont think that you should really require in these specific version.

Any plans on opening up the later versions of console or removing this dependency?

**Comment by mattermack** [comment]
We use console to kick off the ruby backend, as a larger part of Pact community integration.   I am no laravel expert, perhaps we can target specific versions of Symfony/Console.   We currently require: "symfony/console": ">=2.8 <4.1"

Where can I find what Symfony Console dependencies are for larger versions?   I cannot find Console here: https://github.com/laravel/laravel/blob/master/composer.json

In the near term, you could use the PhpPact 2.X branch that does not use Ruby or Symfony/Console.  There are other gotchas around unstable dependencies, which you can find here: https://github.com/pact-foundation/pact-php/tree/2.2.1

**Comment by gradzio** [comment]
alright it seems like we were able to resolve the composer dependency on our end.

**Comment by cfmack** [comment]
I'd actually like to get rid of Symfony as a package dependency all together.   Master currently has the early workings of message bus support.   This resulted in a unique need that I could only get Amp to work with on Windows.  Having both Symfony and Amp for essentially the same problem spaces, I'd like to move to Amp.   However, I have not yet been able to wrap my head around how to pull that off.
