### ISSUE TITLE
Mixing tests against different providers

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#91]
Hi there,

I've started evaluating the new version of this library (using 4.0.2). In my case I am writing a single client that talks to a lot of individual service providers (micro services).

Using the PactListener there is no easy way to change the provider name used AFAIKS. Is this by design or is there a workaround.
I can override the default (from phpunit.xml) for the `InteractionBuilder`, but not the one using the defaults created in the Listener...
I guess I could create test suites for each provider but all mock server would use the same defaults?

**Comment by mattermack** [comment]
@DerManoMann ,  this was an initial implementation, understanding that these cases are complicated.   The general thought was that an end user could always override or create a new listener to suit their unique needs.   If you have a use case beyond that, feel free to make a PR

**Comment by DerManoMann** [comment]
Fair enough - I just wasn't sure if I had missed the point...

I've already created a custom listener and a manager that can handle a separate mock server instance (with incremental port number) for each individual service.

Seeing that micro-services are a big thing I am just a bit surprised that this is considered an edge case...

**Comment by Mpreyzner** [comment]
I'm experiencing the same issue. 

As far as I understand pact is made to test microservices and calling many providers from one consumer is bread and butter of that architecture, hardly an edge case.

In my opinion it would be great if this was  stated clearly in the docs that such case isn't handled with default handler or maybe implement second argument for listener in phpunit config, so we can set provider per test suite at least.
